/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/EpubCLI_html_renderer.o /home/dustin/Documents/EpubCLI/src/nimcache/EpubCLI_html_renderer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_AjV3cEUgs0Y9c7dCt9aItdIA tySequence_AjV3cEUgs0Y9c7dCt9aItdIA;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw {
  RootObj Sup;
NI colonstate_;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ maxSize1;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ offset2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ {
tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg k;
union{
struct {NimStringDesc* fText;
} S1;
struct {NimStringDesc* fTag;
tySequence_AjV3cEUgs0Y9c7dCt9aItdIA* s;
tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* fAttr;
} S2;
} kU;
NI fClientData;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines, void* ClE_0);
void* ClE_0;
} tyProc_yi2DdbHeSfeLfWtzEsHNdg;
typedef N_CLOSURE_PTR(void, TM_W6uXTeFDAZ1n042MaAdEWw_13) (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(void, TM_W6uXTeFDAZ1n042MaAdEWw_28) (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines);
typedef N_CLOSURE_PTR(void, TM_W6uXTeFDAZ1n042MaAdEWw_30) (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines);
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_AjV3cEUgs0Y9c7dCt9aItdIA {
  TGenericSeq Sup;
  tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, renderHtml_e7huUoiU9aQd73rAbOj8bzA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ offset, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ maxSize, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* html, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines, NI scroll);
static N_NIMCALL(void, Marker_tyRef_8LprXJ1vm3KQfQpXjX9aV8g)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NI, len_nNpwpmx4yrat7uqLK78Ljwxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, X5BX5D__jkWgplUGXddn3L7EecYVjgxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n, NI i);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NimStringDesc*, tag_QtoaNWis79bdA859c6he5fbA_4xmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_CLOSURE(void, renderElement_q3xDxnDNjVBl0P8BtretAg)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines, void* ClE_0);
static N_INLINE(tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg, kind_tga3MeAof39b4TZ0fuaeZXgxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, innerText_J8zSYsXiqc2Cue41dd0uuw)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ)(FILE* f, NI x);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_qzZiac2bU6MN74Jc7G9baqw_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_8LprXJ1vm3KQfQpXjX9aV8g_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_4, "n.k == xnElement ", 17);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_5, "s", 1);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_7, "fTag", 4);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_8, "head", 4);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_9, "body", 4);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_10, "div", 3);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_11, "span", 4);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_15, "br", 2);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_16, "", 0);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_17, "p", 1);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_18, "i", 1);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_20, " ", 1);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_22, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_23, "h", 1);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_24, "small", 5);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_25, "big", 3);
STRING_LITERAL(TM_W6uXTeFDAZ1n042MaAdEWw_26, "<BOLD>", 6);
static N_NIMCALL(void, Marker_tyRef_8LprXJ1vm3KQfQpXjX9aV8g)(void* p, NI op) {
	tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw* a;
	a = (tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, len_nNpwpmx4yrat7uqLK78Ljwxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n) {
	NI result;
	nimfr_("len", "xmltree.nim");
	result = (NI)0;
	nimln_(137, "xmltree.nim");
	{
		NI T5_;
		if (!((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1))) goto LA3_;
		if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_5));
		T5_ = ((*n).kU.S2.s ? (*n).kU.S2.s->Sup.len : 0);
		result = T5_;
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, X5BX5D__jkWgplUGXddn3L7EecYVjgxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n, NI i) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	nimfr_("[]", "xmltree.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	nimln_(145, "xmltree.nim");
	{
		if (!!(((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_4));
	}
	LA3_: ;
	nimln_(146, "xmltree.nim");
	if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_5));
	if ((NU)(i) >= (NU)((*n).kU.S2.s->Sup.len)) raiseIndexError();
	result = (*n).kU.S2.s->data[i];
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, tag_QtoaNWis79bdA859c6he5fbA_4xmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n) {
	NimStringDesc* result;
	nimfr_("tag", "xmltree.nim");
	result = (NimStringDesc*)0;
	nimln_(115, "xmltree.nim");
	{
		if (!!(((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_4));
	}
	LA3_: ;
	nimln_(116, "xmltree.nim");
	if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_7));
	result = copyString((*n).kU.S2.fTag);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg, kind_tga3MeAof39b4TZ0fuaeZXgxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n) {
	tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg result;
	nimfr_("kind", "xmltree.nim");
	result = (tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg)0;
	nimln_(141, "xmltree.nim");
	result = (*n).k;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_CLOSURE(void, renderElement_q3xDxnDNjVBl0P8BtretAg)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* body, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines, void* ClE_0) {
	tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw* colonenvP_;
	nimfr_("renderElement", "html_renderer.nim");
{	colonenvP_ = (tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw*) ClE_0;
	nimln_(11, "html_renderer.nim");
	{
		tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg T3_;
		nimln_(398, "system.nim");
		nimln_(11, "html_renderer.nim");
		T3_ = (tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg)0;
		T3_ = kind_tga3MeAof39b4TZ0fuaeZXgxmltree(body);
		if (!!((T3_ == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA4_;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(12, "html_renderer.nim");
	{
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NimStringDesc* T10_;
		NimStringDesc* T12_;
		NimStringDesc* T14_;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T10_ = (NimStringDesc*)0;
		T10_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T9_ = eqStrings(T10_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_9));
		if (T9_) goto LA11_;
		T12_ = (NimStringDesc*)0;
		T12_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T9_ = eqStrings(T12_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_10));
		LA11_: ;
		T8_ = T9_;
		if (T8_) goto LA13_;
		T14_ = (NimStringDesc*)0;
		T14_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T8_ = eqStrings(T14_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_11));
		LA13_: ;
		if (!T8_) goto LA15_;
		{
			tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* sub;
			sub = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
			nimln_(165, "xmltree.nim");
			{
				if (!!(((*body).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA20_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_4));
			}
			LA20_: ;
			{
				NI i;
				NI colontmp_;
				NI T23_;
				NI TM_W6uXTeFDAZ1n042MaAdEWw_12;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(166, "xmltree.nim");
				T23_ = (NI)0;
				T23_ = len_nNpwpmx4yrat7uqLK78Ljwxmltree(body);
				TM_W6uXTeFDAZ1n042MaAdEWw_12 = subInt(T23_, ((NI) 1));
				colontmp_ = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_12);
				nimln_(2045, "system.nim");
				res = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						tyProc_yi2DdbHeSfeLfWtzEsHNdg T26_;
						NI TM_W6uXTeFDAZ1n042MaAdEWw_14;
						if (!(res <= colontmp_)) goto LA25;
						nimln_(2047, "system.nim");
						i = res;
						nimln_(166, "xmltree.nim");
						sub = X5BX5D__jkWgplUGXddn3L7EecYVjgxmltree(body, i);
						nimln_(14, "html_renderer.nim");
						memset((void*)(&T26_), 0, sizeof(T26_));
						T26_.ClP_0 = renderElement_q3xDxnDNjVBl0P8BtretAg; T26_.ClE_0 = colonenvP_;
						T26_.ClE_0? T26_.ClP_0(sub, theLines, T26_.ClE_0):((TM_W6uXTeFDAZ1n042MaAdEWw_13)(T26_.ClP_0))(sub, theLines);
						nimln_(2048, "system.nim");
						TM_W6uXTeFDAZ1n042MaAdEWw_14 = addInt(res, ((NI) 1));
						res = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_14);
					} LA25: ;
				}
			}
		}
	}
	goto LA6_;
	LA15_: ;
	{
		NimStringDesc* T28_;
		NI T31_;
		NimStringDesc* T32_;
		nimln_(15, "html_renderer.nim");
		T28_ = (NimStringDesc*)0;
		T28_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		if (!eqStrings(T28_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_15))) goto LA29_;
		nimln_(16, "html_renderer.nim");
		(*theLines) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*theLines))->Sup, sizeof(NimStringDesc*));
		T31_ = (*theLines)->Sup.len++;
		T32_ = (NimStringDesc*)0;
		T32_ = (*theLines)->data[T31_]; (*theLines)->data[T31_] = copyStringRC1(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_16));
		if (T32_) nimGCunrefNoCycle(T32_);
	}
	goto LA6_;
	LA29_: ;
	{
		NIM_BOOL T34_;
		NimStringDesc* T35_;
		NimStringDesc* T37_;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* splits;
		NimStringDesc* T40_;
		NimStringDesc* line;
		nimln_(17, "html_renderer.nim");
		T34_ = (NIM_BOOL)0;
		T35_ = (NimStringDesc*)0;
		T35_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T34_ = eqStrings(T35_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_17));
		if (T34_) goto LA36_;
		T37_ = (NimStringDesc*)0;
		T37_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T34_ = eqStrings(T37_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_18));
		LA36_: ;
		if (!T34_) goto LA38_;
		nimln_(18, "html_renderer.nim");
		T40_ = (NimStringDesc*)0;
		T40_ = innerText_J8zSYsXiqc2Cue41dd0uuw(body);
		splits = nsuSplitChar(T40_, 32, ((NI) -1));
		nimln_(19, "html_renderer.nim");
		line = copyString(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_16));
		{
			NimStringDesc* split;
			NI i_2;
			NI L;
			NI T42_;
			split = (NimStringDesc*)0;
			nimln_(3805, "system.nim");
			i_2 = ((NI) 0);
			nimln_(3806, "system.nim");
			T42_ = (splits ? splits->Sup.len : 0);
			L = T42_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NimStringDesc* T52_;
					NI TM_W6uXTeFDAZ1n042MaAdEWw_21;
					if (!(i_2 < L)) goto LA44;
					nimln_(3808, "system.nim");
					if ((NU)(i_2) >= (NU)(splits->Sup.len)) raiseIndexError();
					split = splits->data[i_2];
					nimln_(21, "html_renderer.nim");
					{
						NI TM_W6uXTeFDAZ1n042MaAdEWw_19;
						NimStringDesc* T47_;
						NI T50_;
						NimStringDesc* T51_;
						TM_W6uXTeFDAZ1n042MaAdEWw_19 = subInt((*colonenvP_).maxSize1.Field0, (*colonenvP_).offset2.Field1);
						T47_ = (NimStringDesc*)0;
						T47_ = rawNewString(line->Sup.len + split->Sup.len + 1);
appendString(T47_, line);
appendString(T47_, split);
appendString(T47_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_20));
						if (!((NI)(TM_W6uXTeFDAZ1n042MaAdEWw_19) < (T47_ ? T47_->Sup.len : 0))) goto LA48_;
						nimln_(22, "html_renderer.nim");
						(*theLines) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*theLines))->Sup, sizeof(NimStringDesc*));
						T50_ = (*theLines)->Sup.len++;
						T51_ = (NimStringDesc*)0;
						T51_ = (*theLines)->data[T50_]; (*theLines)->data[T50_] = copyStringRC1(line);
						if (T51_) nimGCunrefNoCycle(T51_);
						nimln_(793, "terminal.nim");
						setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ(stdout, (*colonenvP_).offset2.Field0);
						nimln_(24, "html_renderer.nim");
						line = copyString(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_16));
					}
					LA48_: ;
					nimln_(25, "html_renderer.nim");
					T52_ = (NimStringDesc*)0;
					T52_ = rawNewString(split->Sup.len + 1);
appendString(T52_, split);
appendString(T52_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_20));
					line = resizeString(line, T52_->Sup.len + 0);
appendString(line, T52_);
					nimln_(3809, "system.nim");
					TM_W6uXTeFDAZ1n042MaAdEWw_21 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_21);
					nimln_(3810, "system.nim");
					{
						NI T55_;
						T55_ = (splits ? splits->Sup.len : 0);
						if (!!((T55_ == L))) goto LA56_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_22));
					}
					LA56_: ;
				} LA44: ;
			}
		}
	}
	goto LA6_;
	LA38_: ;
	{
		NIM_BOOL T59_;
		NIM_BOOL T60_;
		NimStringDesc* T61_;
		NimStringDesc* T63_;
		NimStringDesc* T65_;
		NI T68_;
		NimStringDesc* T69_;
		NimStringDesc* T70_;
		NI T71_;
		NimStringDesc* T72_;
		NI T73_;
		NimStringDesc* T74_;
		nimln_(27, "html_renderer.nim");
		T59_ = (NIM_BOOL)0;
		T60_ = (NIM_BOOL)0;
		T61_ = (NimStringDesc*)0;
		T61_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T60_ = contains_bKoQGynT9bWCEn79aXG8be9aw(T61_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_23));
		if (T60_) goto LA62_;
		T63_ = (NimStringDesc*)0;
		T63_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T60_ = eqStrings(T63_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_24));
		LA62_: ;
		T59_ = T60_;
		if (T59_) goto LA64_;
		T65_ = (NimStringDesc*)0;
		T65_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(body);
		T59_ = eqStrings(T65_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_25));
		LA64_: ;
		if (!T59_) goto LA66_;
		nimln_(28, "html_renderer.nim");
		(*theLines) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*theLines))->Sup, sizeof(NimStringDesc*));
		T68_ = (*theLines)->Sup.len++;
		T69_ = (NimStringDesc*)0;
		T69_ = (*theLines)->data[T68_]; (*theLines)->data[T68_] = copyStringRC1(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_26));
		if (T69_) nimGCunrefNoCycle(T69_);
		nimln_(29, "html_renderer.nim");
		T70_ = (NimStringDesc*)0;
		T70_ = innerText_J8zSYsXiqc2Cue41dd0uuw(body);
		(*theLines) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*theLines))->Sup, sizeof(NimStringDesc*));
		T71_ = (*theLines)->Sup.len++;
		T72_ = (NimStringDesc*)0;
		T72_ = (*theLines)->data[T71_]; (*theLines)->data[T71_] = copyStringRC1(T70_);
		if (T72_) nimGCunrefNoCycle(T72_);
		nimln_(30, "html_renderer.nim");
		(*theLines) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*theLines))->Sup, sizeof(NimStringDesc*));
		T73_ = (*theLines)->Sup.len++;
		T74_ = (NimStringDesc*)0;
		T74_ = (*theLines)->data[T73_]; (*theLines)->data[T73_] = copyStringRC1(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_16));
		if (T74_) nimGCunrefNoCycle(T74_);
		{
			tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* sub_2;
			sub_2 = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
			nimln_(165, "xmltree.nim");
			{
				if (!!(((*body).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA78_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_4));
			}
			LA78_: ;
			{
				NI i_3;
				NI colontmp__2;
				NI T81_;
				NI TM_W6uXTeFDAZ1n042MaAdEWw_27;
				NI res_2;
				i_3 = (NI)0;
				colontmp__2 = (NI)0;
				nimln_(166, "xmltree.nim");
				T81_ = (NI)0;
				T81_ = len_nNpwpmx4yrat7uqLK78Ljwxmltree(body);
				TM_W6uXTeFDAZ1n042MaAdEWw_27 = subInt(T81_, ((NI) 1));
				colontmp__2 = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_27);
				nimln_(2045, "system.nim");
				res_2 = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						tyProc_yi2DdbHeSfeLfWtzEsHNdg T84_;
						NI TM_W6uXTeFDAZ1n042MaAdEWw_29;
						if (!(res_2 <= colontmp__2)) goto LA83;
						nimln_(2047, "system.nim");
						i_3 = res_2;
						nimln_(166, "xmltree.nim");
						sub_2 = X5BX5D__jkWgplUGXddn3L7EecYVjgxmltree(body, i_3);
						nimln_(32, "html_renderer.nim");
						memset((void*)(&T84_), 0, sizeof(T84_));
						T84_.ClP_0 = renderElement_q3xDxnDNjVBl0P8BtretAg; T84_.ClE_0 = colonenvP_;
						T84_.ClE_0? T84_.ClP_0(sub_2, theLines, T84_.ClE_0):((TM_W6uXTeFDAZ1n042MaAdEWw_28)(T84_.ClP_0))(sub_2, theLines);
						nimln_(2048, "system.nim");
						TM_W6uXTeFDAZ1n042MaAdEWw_29 = addInt(res_2, ((NI) 1));
						res_2 = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_29);
					} LA83: ;
				}
			}
		}
	}
	goto LA6_;
	LA66_: ;
	{
	}
	LA6_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, renderHtml_e7huUoiU9aQd73rAbOj8bzA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ offset, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ maxSize, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* html, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** theLines, NI scroll) {
	tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw* colonenv_;
	nimfr_("renderHtml", "html_renderer.nim");
	colonenv_ = (tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw*)0;
	nimln_(9, "html_renderer.nim");
	colonenv_ = (tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw*) newObj((&NTI_8LprXJ1vm3KQfQpXjX9aV8g_), sizeof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw));
	(*colonenv_).Sup.m_type = (&NTI_qzZiac2bU6MN74Jc7G9baqw_);
	(*colonenv_).offset2 = offset;
	(*colonenv_).maxSize1 = maxSize;
	{
		tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* part;
		part = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
		nimln_(165, "xmltree.nim");
		{
			if (!!(((*html).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA4_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_4));
		}
		LA4_: ;
		{
			NI i;
			NI colontmp_;
			NI T7_;
			NI TM_W6uXTeFDAZ1n042MaAdEWw_6;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(166, "xmltree.nim");
			T7_ = (NI)0;
			T7_ = len_nNpwpmx4yrat7uqLK78Ljwxmltree(html);
			TM_W6uXTeFDAZ1n042MaAdEWw_6 = subInt(T7_, ((NI) 1));
			colontmp_ = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_6);
			nimln_(2045, "system.nim");
			res = ((NI) 0);
			{
				nimln_(2046, "system.nim");
				while (1) {
					NI TM_W6uXTeFDAZ1n042MaAdEWw_31;
					if (!(res <= colontmp_)) goto LA9;
					nimln_(2047, "system.nim");
					i = res;
					nimln_(166, "xmltree.nim");
					part = X5BX5D__jkWgplUGXddn3L7EecYVjgxmltree(html, i);
					nimln_(35, "html_renderer.nim");
					{
						NimStringDesc* T12_;
						T12_ = (NimStringDesc*)0;
						T12_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(part);
						if (!eqStrings(T12_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_8))) goto LA13_;
					}
					goto LA10_;
					LA13_: ;
					{
						nimln_(39, "html_renderer.nim");
						{
							NimStringDesc* T18_;
							tyProc_yi2DdbHeSfeLfWtzEsHNdg T21_;
							T18_ = (NimStringDesc*)0;
							T18_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(part);
							if (!eqStrings(T18_, ((NimStringDesc*) &TM_W6uXTeFDAZ1n042MaAdEWw_9))) goto LA19_;
							nimln_(40, "html_renderer.nim");
							memset((void*)(&T21_), 0, sizeof(T21_));
							T21_.ClP_0 = renderElement_q3xDxnDNjVBl0P8BtretAg; T21_.ClE_0 = colonenv_;
							T21_.ClE_0? T21_.ClP_0(part, theLines, T21_.ClE_0):((TM_W6uXTeFDAZ1n042MaAdEWw_30)(T21_.ClP_0))(part, theLines);
						}
						LA19_: ;
					}
					LA10_: ;
					nimln_(2048, "system.nim");
					TM_W6uXTeFDAZ1n042MaAdEWw_31 = addInt(res, ((NI) 1));
					res = (NI)(TM_W6uXTeFDAZ1n042MaAdEWw_31);
				} LA9: ;
			}
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, EpubCLI_html_rendererInit000)(void) {
	nimfr_("html_renderer", "html_renderer.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, EpubCLI_html_rendererDatInit000)(void) {
static TNimNode* TM_W6uXTeFDAZ1n042MaAdEWw_2[3];
static TNimNode* TM_W6uXTeFDAZ1n042MaAdEWw_3[2];
static TNimNode TM_W6uXTeFDAZ1n042MaAdEWw_0[7];
NTI_qzZiac2bU6MN74Jc7G9baqw_.size = sizeof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw);
NTI_qzZiac2bU6MN74Jc7G9baqw_.kind = 17;
NTI_qzZiac2bU6MN74Jc7G9baqw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_qzZiac2bU6MN74Jc7G9baqw_.flags = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_2[0] = &TM_W6uXTeFDAZ1n042MaAdEWw_0[1];
TM_W6uXTeFDAZ1n042MaAdEWw_0[1].kind = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_0[1].offset = offsetof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw, colonstate_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[1].name = ":state";
TM_W6uXTeFDAZ1n042MaAdEWw_2[1] = &TM_W6uXTeFDAZ1n042MaAdEWw_0[2];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.size = sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.flags = 3;
TM_W6uXTeFDAZ1n042MaAdEWw_3[0] = &TM_W6uXTeFDAZ1n042MaAdEWw_0[4];
TM_W6uXTeFDAZ1n042MaAdEWw_0[4].kind = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_0[4].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
TM_W6uXTeFDAZ1n042MaAdEWw_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[4].name = "Field0";
TM_W6uXTeFDAZ1n042MaAdEWw_3[1] = &TM_W6uXTeFDAZ1n042MaAdEWw_0[5];
TM_W6uXTeFDAZ1n042MaAdEWw_0[5].kind = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_0[5].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
TM_W6uXTeFDAZ1n042MaAdEWw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[5].name = "Field1";
TM_W6uXTeFDAZ1n042MaAdEWw_0[3].len = 2; TM_W6uXTeFDAZ1n042MaAdEWw_0[3].kind = 2; TM_W6uXTeFDAZ1n042MaAdEWw_0[3].sons = &TM_W6uXTeFDAZ1n042MaAdEWw_3[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.node = &TM_W6uXTeFDAZ1n042MaAdEWw_0[3];
TM_W6uXTeFDAZ1n042MaAdEWw_0[2].kind = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_0[2].offset = offsetof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw, maxSize1);
TM_W6uXTeFDAZ1n042MaAdEWw_0[2].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[2].name = "maxSize1";
TM_W6uXTeFDAZ1n042MaAdEWw_2[2] = &TM_W6uXTeFDAZ1n042MaAdEWw_0[6];
TM_W6uXTeFDAZ1n042MaAdEWw_0[6].kind = 1;
TM_W6uXTeFDAZ1n042MaAdEWw_0[6].offset = offsetof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw, offset2);
TM_W6uXTeFDAZ1n042MaAdEWw_0[6].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_W6uXTeFDAZ1n042MaAdEWw_0[6].name = "offset2";
TM_W6uXTeFDAZ1n042MaAdEWw_0[0].len = 3; TM_W6uXTeFDAZ1n042MaAdEWw_0[0].kind = 2; TM_W6uXTeFDAZ1n042MaAdEWw_0[0].sons = &TM_W6uXTeFDAZ1n042MaAdEWw_2[0];
NTI_qzZiac2bU6MN74Jc7G9baqw_.node = &TM_W6uXTeFDAZ1n042MaAdEWw_0[0];
NTI_8LprXJ1vm3KQfQpXjX9aV8g_.size = sizeof(tyObject_Env_html_rendererdotnim__qzZiac2bU6MN74Jc7G9baqw*);
NTI_8LprXJ1vm3KQfQpXjX9aV8g_.kind = 22;
NTI_8LprXJ1vm3KQfQpXjX9aV8g_.base = (&NTI_qzZiac2bU6MN74Jc7G9baqw_);
NTI_8LprXJ1vm3KQfQpXjX9aV8g_.marker = Marker_tyRef_8LprXJ1vm3KQfQpXjX9aV8g;
}

