/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_os.o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_os.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <dirent.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
typedef long tyArray_QS4edQct6fXoghbs69aZ9a8w[3];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg;
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef char tyArray_XKk9bNZbVEtY3RuROG9aRBgw[256];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringDesc* file);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsOrCreateDir_V86QyZrcGMPX0W9bv1Q53ww)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir_V86QyZrcGMPX0W9bv1Q53ww_2)(NimStringDesc* dir);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem)(NimStringDesc* s, NI i);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, expandTilde_DOCYVvghSr9cSjyIq0voF3g)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSymlink_KkZgXPy74tXi49bh8QSie8g)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogos)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, rawRemoveDir_P9aOuM3pg25yKqgBUm7qKng)(NimStringDesc* dir);
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_4, "", 0);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_5, "Failed to create the directory", 30);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_10, "PATH", 4);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_18, ".", 1);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_19, "..", 2);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_20, "\012not (path == \"\") ", 18);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI T1_;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_2;
	nimfr_("pop", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(2431, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_yu6cxgKBBXbNsTkT9cyMd4g_2 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_2);
	nimln_(2432, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln_(2433, "system.nim");
	(*s) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("existsFile", "os.nim");
{	result = (NIM_BOOL)0;
	memset((void*)(&res), 0, sizeof(res));
	nimln_(83, "os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(filename->data, (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISREG(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringDesc* file) {
	NIM_BOOL result;
	nimfr_("tryRemoveFile", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(566, "os.nim");
	result = NIM_TRUE;
	nimln_(582, "os.nim");
	{
		NIM_BOOL T3_;
		int T4_;
		T3_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(582, "os.nim");
		T4_ = (int)0;
		T4_ = remove(file->data);
		T3_ = !((T4_ == ((NI32) 0)));
		if (!(T3_)) goto LA5_;
		nimln_(398, "system.nim");
		nimln_(582, "os.nim");
		T3_ = !((errno == ((int) 2)));
		LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(583, "os.nim");
		result = NIM_FALSE;
	}
	LA6_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file) {
	nimfr_("removeFile", "os.nim");
	nimln_(589, "os.nim");
	{
		NIM_BOOL T3_;
		NI32 T6_;
		NCSTRING T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = nostryRemoveFile(file);
		if (!!(T3_)) goto LA4_;
		nimln_(593, "os.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T7_ = (NCSTRING)0;
		T7_ = strerror(errno);
		T8_ = (NimStringDesc*)0;
		T8_ = cstrToNimstr(T7_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, T8_);
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir_V86QyZrcGMPX0W9bv1Q53ww_2)(NimStringDesc* dir) {
	NIM_BOOL result;
	int res;
	nimfr_("rawCreateDir", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(906, "os.nim");
	res = mkdir(dir->data, ((mode_t) 511));
	nimln_(907, "os.nim");
	{
		if (!(res == ((NI32) 0))) goto LA3_;
		nimln_(908, "os.nim");
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(909, "os.nim");
		if (!(errno == ((int) 17))) goto LA6_;
		nimln_(910, "os.nim");
		result = NIM_FALSE;
	}
	goto LA1_;
	LA6_: ;
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T9_;
		NI32 T10_;
		nimln_(912, "os.nim");
		memset((void*)T9_, 0, sizeof(T9_));
		T9_[0] = nimIntToStr(((NI) (res)));
		echoBinSafe(T9_, 1);
		nimln_(913, "os.nim");
		T10_ = (NI32)0;
		T10_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T10_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("existsDir", "os.nim");
{	result = (NIM_BOOL)0;
	memset((void*)(&res), 0, sizeof(res));
	nimln_(97, "os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(dir->data, (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISDIR(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsOrCreateDir_V86QyZrcGMPX0W9bv1Q53ww)(NimStringDesc* dir) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("existsOrCreateDir", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(933, "os.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = rawCreateDir_V86QyZrcGMPX0W9bv1Q53ww_2(dir);
	result = !(T1_);
	nimln_(934, "os.nim");
	{
		if (!result) goto LA4_;
		nimln_(936, "os.nim");
		{
			NIM_BOOL T8_;
			tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
			NimStringDesc* T11_;
			T8_ = (NIM_BOOL)0;
			T8_ = nosexistsDir(dir);
			if (!!(T8_)) goto LA9_;
			e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
			nimln_(2811, "system.nim");
			e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
			(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
			nimln_(937, "os.nim");
			T11_ = (NimStringDesc*)0;
			T11_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_5));
			if (T11_) nimGCunrefNoCycle(T11_);
			nimln_(2806, "system.nim");
			asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
			nimln_(937, "os.nim");
			raiseException((Exception*)e, "IOError");
		}
		LA9_: ;
	}
	LA4_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem)(NimStringDesc* s, NI i) {
	NIM_CHAR result;
	NI TM_yu6cxgKBBXbNsTkT9cyMd4g_8;
	nimfr_("[]", "system.nim");
	result = (NIM_CHAR)0;
	nimln_(3626, "system.nim");
	TM_yu6cxgKBBXbNsTkT9cyMd4g_8 = subInt((s ? s->Sup.len : 0), i);
	if ((NU)((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_8)) > (NU)(s->Sup.len)) raiseIndexError();
	result = s->data[(NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_8)];
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringDesc* dir) {
	NIM_BOOL omitNext;
	nimfr_("createDir", "os.nim");
	nimln_(947, "os.nim");
	omitNext = NIM_FALSE;
	{
		NI i;
		NI colontmp_;
		NI TM_yu6cxgKBBXbNsTkT9cyMd4g_3;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(950, "os.nim");
		TM_yu6cxgKBBXbNsTkT9cyMd4g_3 = subInt((dir ? dir->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_3);
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_7;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(951, "os.nim");
				{
					if ((NU)(i) > (NU)(dir->Sup.len)) raiseIndexError();
					if (!(((NU8)(dir->data[i])) == ((NU8)(47)) || ((NU8)(dir->data[i])) == ((NU8)(47)))) goto LA6_;
					nimln_(952, "os.nim");
					{
						if (!omitNext) goto LA10_;
						nimln_(953, "os.nim");
						omitNext = NIM_FALSE;
					}
					goto LA8_;
					LA10_: ;
					{
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_6;
						NimStringDesc* T13_;
						NIM_BOOL T14_;
						nimln_(955, "os.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_6 = subInt(i, ((NI) 1));
						T13_ = (NimStringDesc*)0;
						T13_ = copyStrLast(dir, ((NI) 0), (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_6));
						T14_ = (NIM_BOOL)0;
						T14_ = existsOrCreateDir_V86QyZrcGMPX0W9bv1Q53ww(T13_);
						T14_;
					}
					LA8_: ;
				}
				LA6_: ;
				nimln_(2048, "system.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_7 = addInt(res, ((NI) 1));
				res = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_7);
			} LA3: ;
		}
	}
	nimln_(958, "os.nim");
	{
		NIM_BOOL T17_;
		NIM_BOOL T18_;
		NIM_CHAR T21_;
		NIM_BOOL T24_;
		T17_ = (NIM_BOOL)0;
		T18_ = (NIM_BOOL)0;
		T18_ = (((NI) 0) < (dir ? dir->Sup.len : 0));
		if (!(T18_)) goto LA19_;
		T18_ = !(omitNext);
		LA19_: ;
		T17_ = T18_;
		if (!(T17_)) goto LA20_;
		nimln_(1212, "system.nim");
		nimln_(959, "os.nim");
		T21_ = (NIM_CHAR)0;
		T21_ = X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgsystem(dir, ((NI) 1));
		T17_ = !((((NU8)(T21_)) == ((NU8)(47)) || ((NU8)(T21_)) == ((NU8)(47))));
		LA20_: ;
		if (!T17_) goto LA22_;
		nimln_(960, "os.nim");
		T24_ = (NIM_BOOL)0;
		T24_ = existsOrCreateDir_V86QyZrcGMPX0W9bv1Q53ww(dir);
		T24_;
	}
	LA22_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSymlink_KkZgXPy74tXi49bh8QSie8g)(NimStringDesc* path) {
	NIM_BOOL result;
	struct stat rawInfo;
	nimfr_("checkSymlink", "os.nim");
	result = (NIM_BOOL)0;
	memset((void*)(&rawInfo), 0, sizeof(rawInfo));
	nimln_(125, "os.nim");
	{
		int T3_;
		T3_ = (int)0;
		T3_ = lstat(path->data, (&rawInfo));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(126, "os.nim");
		result = S_ISLNK(rawInfo.st_mode);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, findExe_XcLgn9booQ6akyBsF074Lfw)(NimStringDesc* exe, NIM_BOOL followSymlinks, NimStringDesc** extensions, NI extensionsLen_0) {
	NimStringDesc* result;
	NimStringDesc* path;
	nimfr_("findExe", "os.nim");
{	result = (NimStringDesc*)0;
	nimln_(147, "os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_6e5MGL10HDAJ205lBYpWxw(exe, 47);
		if (!T3_) goto LA4_;
		{
			NimStringDesc* ext;
			NI i;
			ext = (NimStringDesc*)0;
			nimln_(2185, "system.nim");
			i = ((NI) 0);
			{
				nimln_(2186, "system.nim");
				while (1) {
					NI TM_yu6cxgKBBXbNsTkT9cyMd4g_9;
					if (!(i < extensionsLen_0)) goto LA8;
					nimln_(2187, "system.nim");
					if ((NU)(i) >= (NU)(extensionsLen_0)) raiseIndexError();
					ext = extensions[i];
					nimln_(144, "os.nim");
					result = nosaddFileExt(exe, ext);
					nimln_(145, "os.nim");
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = nosexistsFile(result);
						if (!T11_) goto LA12_;
						goto BeforeRet_;
					}
					LA12_: ;
					nimln_(2188, "system.nim");
					TM_yu6cxgKBBXbNsTkT9cyMd4g_9 = addInt(i, ((NI) 1));
					i = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_9);
				} LA8: ;
			}
		}
	}
	LA4_: ;
	nimln_(150, "os.nim");
	path = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_10), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	{
		NimStringDesc* candidate;
		NI last;
		NI splits;
		candidate = (NimStringDesc*)0;
		nimln_(502, "strutils.nim");
		last = ((NI) 0);
		nimln_(503, "strutils.nim");
		splits = ((NI) -1);
		{
			nimln_(641, "strutils.nim");
			while (1) {
				NI first;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_12;
				NimStringDesc* x;
				NimStringDesc* T25_;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_15;
				NI TM_yu6cxgKBBXbNsTkT9cyMd4g_16;
				nimln_(505, "strutils.nim");
				nimln_(641, "strutils.nim");
				if (!(last <= (path ? path->Sup.len : 0))) goto LA16;
				nimln_(506, "strutils.nim");
				first = last;
				{
					nimln_(507, "strutils.nim");
					while (1) {
						NIM_BOOL T19_;
						NI TM_yu6cxgKBBXbNsTkT9cyMd4g_11;
						T19_ = (NIM_BOOL)0;
						nimln_(641, "strutils.nim");
						T19_ = (last < (path ? path->Sup.len : 0));
						if (!(T19_)) goto LA20_;
						nimln_(507, "strutils.nim");
						nimln_(495, "strutils.nim");
						if ((NU)(last) > (NU)(path->Sup.len)) raiseIndexError();
						T19_ = !(((NU8)(path->data[last]) == (NU8)(58)));
						LA20_: ;
						if (!T19_) goto LA18;
						nimln_(508, "strutils.nim");
						TM_yu6cxgKBBXbNsTkT9cyMd4g_11 = addInt(last, ((NI) 1));
						last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_11);
					} LA18: ;
				}
				nimln_(509, "strutils.nim");
				{
					if (!(splits == ((NI) 0))) goto LA23_;
					nimln_(641, "strutils.nim");
					last = (path ? path->Sup.len : 0);
				}
				LA23_: ;
				nimln_(510, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_12 = subInt(last, ((NI) 1));
				candidate = copyStrLast(path, first, (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_12));
				nimln_(157, "os.nim");
				T25_ = (NimStringDesc*)0;
				T25_ = expandTilde_DOCYVvghSr9cSjyIq0voF3g(candidate);
				x = slash__lXoMhn1ZYc9cAJa9bfA61msg(T25_, exe);
				{
					NimStringDesc* ext_2;
					NI i_2;
					ext_2 = (NimStringDesc*)0;
					nimln_(2185, "system.nim");
					i_2 = ((NI) 0);
					{
						nimln_(2186, "system.nim");
						while (1) {
							NimStringDesc* x_2;
							NI TM_yu6cxgKBBXbNsTkT9cyMd4g_14;
							if (!(i_2 < extensionsLen_0)) goto LA28;
							nimln_(2187, "system.nim");
							if ((NU)(i_2) >= (NU)(extensionsLen_0)) raiseIndexError();
							ext_2 = extensions[i_2];
							nimln_(159, "os.nim");
							x_2 = nosaddFileExt(x, ext_2);
							nimln_(160, "os.nim");
							{
								NIM_BOOL T31_;
								T31_ = (NIM_BOOL)0;
								T31_ = nosexistsFile(x_2);
								if (!T31_) goto LA32_;
								{
									nimln_(162, "os.nim");
									while (1) {
										if (!followSymlinks) goto LA35;
										nimln_(163, "os.nim");
										{
											NIM_BOOL T38_;
											NimStringDesc* r;
											NI len;
											T38_ = (NIM_BOOL)0;
											T38_ = checkSymlink_KkZgXPy74tXi49bh8QSie8g(x_2);
											if (!T38_) goto LA39_;
											nimln_(164, "os.nim");
											r = mnewString(((NI) 256));
											nimln_(165, "os.nim");
											len = readlink(x_2->data, r->data, ((NI) 256));
											nimln_(166, "os.nim");
											{
												NI32 T45_;
												if (!(len < ((NI) 0))) goto LA43_;
												nimln_(167, "os.nim");
												T45_ = (NI32)0;
												T45_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
												raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T45_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
											}
											LA43_: ;
											nimln_(168, "os.nim");
											{
												NI TM_yu6cxgKBBXbNsTkT9cyMd4g_13;
												if (!(((NI) 256) < len)) goto LA48_;
												nimln_(169, "os.nim");
												TM_yu6cxgKBBXbNsTkT9cyMd4g_13 = addInt(len, ((NI) 1));
												r = mnewString(((NI)chckRange((NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_13), ((NI) 0), ((NI) IL64(9223372036854775807)))));
												nimln_(170, "os.nim");
												len = readlink(x_2->data, r->data, len);
											}
											LA48_: ;
											nimln_(171, "os.nim");
											r = setLengthStr(r, ((NI)chckRange(len, ((NI) 0), ((NI) IL64(9223372036854775807)))));
											nimln_(172, "os.nim");
											{
												NIM_BOOL T52_;
												T52_ = (NIM_BOOL)0;
												T52_ = nosisAbsolute(r);
												if (!T52_) goto LA53_;
												nimln_(173, "os.nim");
												x_2 = copyString(r);
											}
											goto LA50_;
											LA53_: ;
											{
												NimStringDesc* T56_;
												nimln_(175, "os.nim");
												T56_ = (NimStringDesc*)0;
												T56_ = nosparentDir(x_2);
												x_2 = slash__lXoMhn1ZYc9cAJa9bfA61msg(T56_, r);
											}
											LA50_: ;
										}
										goto LA36_;
										LA39_: ;
										{
											nimln_(177, "os.nim");
											goto LA34;
										}
										LA36_: ;
									} LA35: ;
								} LA34: ;
								nimln_(178, "os.nim");
								result = copyString(x_2);
								goto BeforeRet_;
							}
							LA32_: ;
							nimln_(2188, "system.nim");
							TM_yu6cxgKBBXbNsTkT9cyMd4g_14 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_14);
						} LA28: ;
					}
				}
				nimln_(511, "strutils.nim");
				{
					if (!(splits == ((NI) 0))) goto LA60_;
					goto LA15;
				}
				LA60_: ;
				nimln_(512, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_15 = subInt(splits, ((NI) 1));
				splits = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_15);
				nimln_(513, "strutils.nim");
				TM_yu6cxgKBBXbNsTkT9cyMd4g_16 = addInt(last, ((NI) 1));
				last = (NI)(TM_yu6cxgKBBXbNsTkT9cyMd4g_16);
			} LA16: ;
		} LA15: ;
	}
	nimln_(179, "os.nim");
	result = copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, dirExists_wf0Ae3eLXw0lSNEFJMV3ogos)(NimStringDesc* dir) {
	NIM_BOOL result;
	nimfr_("dirExists", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(119, "os.nim");
	nimln_(120, "os.nim");
	result = nosexistsDir(dir);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg, getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg)(NimStringDesc* path) {
	tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg result;
	struct stat s;
	nimfr_("getSymlinkFileKind", "os.nim");
	result = (tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
	memset((void*)(&s), 0, sizeof(s));
	nimln_(738, "os.nim");
	{
		if (!!(!(((path) && (path)->Sup.len == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_20));
	}
	LA3_: ;
	nimln_(739, "os.nim");
	{
		int T7_;
		NI32 T10_;
		T7_ = (int)0;
		T7_ = stat(path->data, (&s));
		if (!(T7_ < ((NI32) 0))) goto LA8_;
		nimln_(740, "os.nim");
		T10_ = (NI32)0;
		T10_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T10_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	}
	LA8_: ;
	nimln_(741, "os.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = S_ISDIR(s.st_mode);
		if (!T13_) goto LA14_;
		nimln_(742, "os.nim");
		result = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
	}
	goto LA11_;
	LA14_: ;
	{
		nimln_(744, "os.nim");
		result = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
	}
	LA11_: ;
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_LIB_PRIVATE N_NIMCALL(void, rawRemoveDir_P9aOuM3pg25yKqgBUm7qKng)(NimStringDesc* dir) {
	nimfr_("rawRemoveDir", "os.nim");
	nimln_(876, "os.nim");
	{
		NIM_BOOL T3_;
		int T4_;
		NI32 T8_;
		T3_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(876, "os.nim");
		T4_ = (int)0;
		T4_ = rmdir(dir->data);
		T3_ = !((T4_ == ((NI32) 0)));
		if (!(T3_)) goto LA5_;
		nimln_(398, "system.nim");
		nimln_(876, "os.nim");
		T3_ = !((errno == ((int) 2)));
		LA5_: ;
		if (!T3_) goto LA6_;
		T8_ = (NI32)0;
		T8_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T8_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	}
	LA6_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir) {
	nimfr_("removeDir", "os.nim");
	{
		tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg kind;
		NimStringDesc* path;
		DIR* d;
		kind = (tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg)0;
		path = (NimStringDesc*)0;
		nimln_(798, "os.nim");
		d = opendir(dir->data);
		nimln_(799, "os.nim");
		{
			TSafePoint TM_yu6cxgKBBXbNsTkT9cyMd4g_17;
			nimln_(398, "system.nim");
			nimln_(799, "os.nim");
			if (!!((d == NIM_NIL))) goto LA4_;
			nimln_(800, "os.nim");
			pushSafePoint(&TM_yu6cxgKBBXbNsTkT9cyMd4g_17);
			TM_yu6cxgKBBXbNsTkT9cyMd4g_17.status = setjmp(TM_yu6cxgKBBXbNsTkT9cyMd4g_17.context);
			if (TM_yu6cxgKBBXbNsTkT9cyMd4g_17.status == 0) {
				{
					nimln_(801, "os.nim");
					while (1) {
						{
							struct dirent* x;
							NimStringDesc* volatile y;
							nimln_(802, "os.nim");
							x = readdir(d);
							nimln_(803, "os.nim");
							{
								if (!(x == NIM_NIL)) goto LA12_;
								goto LA7;
							}
							LA12_: ;
							nimln_(805, "os.nim");
							y = cstrToNimstr(((NCSTRING) ((*x).d_name)));
							nimln_(808, "os.nim");
							{
								NIM_BOOL T16_;
								struct stat s;
								tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg volatile k;
								T16_ = (NIM_BOOL)0;
								nimln_(398, "system.nim");
								nimln_(808, "os.nim");
								T16_ = !(eqStrings(y, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_18)));
								if (!(T16_)) goto LA17_;
								nimln_(398, "system.nim");
								nimln_(808, "os.nim");
								T16_ = !(eqStrings(y, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_19)));
								LA17_: ;
								if (!T16_) goto LA18_;
								memset((void*)(&s), 0, sizeof(s));
								nimln_(810, "os.nim");
								{
									if (!NIM_TRUE) goto LA22_;
									nimln_(811, "os.nim");
									y = slash__lXoMhn1ZYc9cAJa9bfA61msg(dir, y);
								}
								LA22_: ;
								nimln_(812, "os.nim");
								k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0);
								nimln_(815, "os.nim");
								{
									nimln_(398, "system.nim");
									nimln_(815, "os.nim");
									if (!!(((*x).d_type == ((NI8) 0)))) goto LA26_;
									nimln_(816, "os.nim");
									{
										if (!((*x).d_type == ((NI8) 4))) goto LA30_;
										k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
									}
									LA30_: ;
									nimln_(817, "os.nim");
									{
										if (!((*x).d_type == ((NI8) 10))) goto LA34_;
										nimln_(818, "os.nim");
										{
											NIM_BOOL T38_;
											T38_ = (NIM_BOOL)0;
											T38_ = dirExists_wf0Ae3eLXw0lSNEFJMV3ogos(y);
											if (!T38_) goto LA39_;
											k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3);
										}
										goto LA36_;
										LA39_: ;
										{
											nimln_(819, "os.nim");
											k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1);
										}
										LA36_: ;
									}
									LA34_: ;
									nimln_(820, "os.nim");
									kind = k;
									path = y;
									nimln_(886, "os.nim");
									switch (kind) {
									case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0):
									case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1):
									case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3):
									{
										nimln_(887, "os.nim");
										nosremoveFile(path);
									}
									break;
									case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2):
									{
										nimln_(888, "os.nim");
										nosremoveDir(path);
									}
									break;
									}
									nimln_(821, "os.nim");
									goto LA9;
								}
								LA26_: ;
								nimln_(823, "os.nim");
								{
									int T46_;
									T46_ = (int)0;
									T46_ = lstat(y->data, (&s));
									if (!(T46_ < ((NI32) 0))) goto LA47_;
									goto LA7;
								}
								LA47_: ;
								nimln_(824, "os.nim");
								{
									NIM_BOOL T51_;
									T51_ = (NIM_BOOL)0;
									T51_ = S_ISDIR(s.st_mode);
									if (!T51_) goto LA52_;
									nimln_(825, "os.nim");
									k = ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2);
								}
								goto LA49_;
								LA52_: ;
								{
									NIM_BOOL T55_;
									nimln_(826, "os.nim");
									T55_ = (NIM_BOOL)0;
									T55_ = S_ISLNK(s.st_mode);
									if (!T55_) goto LA56_;
									nimln_(827, "os.nim");
									k = getSymlinkFileKind_WoXOp8qmMec1P4MyA3LBKg(y);
								}
								goto LA49_;
								LA56_: ;
								LA49_: ;
								nimln_(828, "os.nim");
								kind = k;
								path = y;
								nimln_(886, "os.nim");
								switch (kind) {
								case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 0):
								case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 1):
								case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 3):
								{
									nimln_(887, "os.nim");
									nosremoveFile(path);
								}
								break;
								case ((tyEnum_PathComponent_9c1SIU9cO1wHcl09b703A9cDrg) 2):
								{
									nimln_(888, "os.nim");
									nosremoveDir(path);
								}
								break;
								}
							}
							LA18_: ;
						} LA9: ;
					}
				} LA7: ;
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR_);
			}
			{
				int T62_;
				nimln_(800, "os.nim");
				T62_ = (int)0;
				T62_ = closedir(d);
				T62_;
			}
			if (TM_yu6cxgKBBXbNsTkT9cyMd4g_17.status != 0) reraiseException();
		}
		LA4_: ;
	}
	nimln_(889, "os.nim");
	rawRemoveDir_P9aOuM3pg25yKqgBUm7qKng(dir);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
	nimfr_("os", "os.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

