/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_xmlparser.o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_xmlparser.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ;
typedef struct tySequence_AjV3cEUgs0Y9c7dCt9aItdIA tySequence_AjV3cEUgs0Y9c7dCt9aItdIA;
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg;
typedef struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* errors;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg;
struct tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ {
tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg k;
union{
struct {NimStringDesc* fText;
} S1;
struct {NimStringDesc* fTag;
tySequence_AjV3cEUgs0Y9c7dCt9aItdIA* s;
tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* fAttr;
} S2;
} kU;
NI fClientData;
};
typedef NU8 tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ;
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw;
typedef NU8 tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg;
typedef NU8 tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ;
struct tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg {
  tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
NimStringDesc* a;
NimStringDesc* b;
NimStringDesc* c;
tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ kind;
tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw err;
tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg state;
NimStringDesc* filename;
tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ options;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef tyTuple_UV3llMMYFckfui8YMBuUZA tyArray_9cQD2Rag5wSTKjlY7q5DZNg[1];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_AjV3cEUgs0Y9c7dCt9aItdIA {
  TGenericSeq Sup;
  tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, raiseInvalidXml_VMPgMzv9a9bcKoG3r9cZEbEeg)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* errors);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_skKOuFAXYIMNcqnreZoFeQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, addNode_zyp9bPAuusjaEVd4gOCiNhQ)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* father, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* son);
static N_INLINE(void, add_IfMT5tPSNLKQQespGYVK4gxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* father, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* son);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, untilElementEnd_VysJIpEBv2RXMaExkvp9aiQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* x, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors);
static N_INLINE(tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ, kind_N0M9awVoW5JGLxQwzrpfHgAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NimStringDesc*, tag_QtoaNWis79bdA859c6he5fbA_4xmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, next_l7IS2MtBiHyCD179axgTwXw_11)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_YIH03aH6dy2ESIzuZxY0yQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parse_1kYxdgK5JgAL5wWwEf3kGw)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* x, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, newComment_XIJqUJEpTq2bai9bulcUi9bg)(NimStringDesc* comment);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, newText_qt1k3g1aYfrKRVDFYKeG3A)(NimStringDesc* text);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_OuAOoG9bITnB870Ba1n7ysA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, newElement_uONDNX4Q6ri9c9cSfLIvv8DQ)(NimStringDesc* tag);
static N_INLINE(void, attrseq__n1dueK1BMvuSCXgFQEIhvwxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n, tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* attr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, attrs_2QT0Y19bvocFDK3gux9c644Qxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, newCData_WuMZkkUy9cJG3jFSbh019avw)(NimStringDesc* cdata);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, newEntity_9ctb9aQYaBwNTYctI3EKuEvQ)(NimStringDesc* entity);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parseXml_iqQOZrmB4Y9ciOe5n4tpMxw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc* filename, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors);
N_LIB_PRIVATE N_NIMCALL(void, open_V2ukTv2NIJNJ3rLrjojBGA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ options);
static N_INLINE(void, close_Oot2zKx9cpsstnS9bf7hZfVAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parseXml_37vKClm3NqjjKqbh2a689aw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, loadXml_9aDY8nkp5finOQtxIc7OvpQ)(NimStringDesc* path, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_9argyMqCIlB1KDaxUuYVcmw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, loadXml_9a1UKxr09afI9bxerDMiekk9cw)(NimStringDesc* path);
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_Bna0dsG6RR1XOB0smpGHtw_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_skKOuFAXYIMNcqnreZoFeQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_AbcNJUHmXZCVg300UxOzLg_;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_2, "s", 1);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_3, "contains({xmlElementStart, xmlElementEnd, xmlElementOpen}, x.ki"
"nd) ", 67);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_4, "n.k == xnElement ", 17);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_5, "fTag", 4);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_6, "</", 2);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_7, "> expected", 10);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_8, "contains({xmlCharData, xmlWhitespace, xmlComment, xmlCData, xml"
"Special}, x.kind) ", 81);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_9, "unexpected ending tag: ", 23);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_10, "fAttr", 5);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_11, "x.kind == xmlAttribute ", 23);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_12, "\'>\' expected", 12);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_13, "<some_tag> expected", 19);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_14, "x.kind == xmlEntity ", 20);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_15, "unknown_html_doc", 16);
STRING_LITERAL(TM_u0mC1ER8iy09bE9aXHBhXAXw_16, "Unable to read file: ", 21);
static N_NIMCALL(void, Marker_tyRef_skKOuFAXYIMNcqnreZoFeQ)(void* p, NI op) {
	tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw* a;
	a = (tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
	nimGCvisit((void*)(*a).errors, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, raiseInvalidXml_VMPgMzv9a9bcKoG3r9cZEbEeg)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* errors) {
	tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw* e;
	NimStringDesc* T1_;
	nimfr_("raiseInvalidXml", "xmlparser.nim");
	e = (tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw*)0;
	nimln_(23, "xmlparser.nim");
	e = (tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw*) newObj((&NTI_skKOuFAXYIMNcqnreZoFeQ_), sizeof(tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw));
	(*e).Sup.Sup.Sup.m_type = (&NTI_Bna0dsG6RR1XOB0smpGHtw_);
	nimln_(24, "xmlparser.nim");
	if ((NU)(((NI) 0)) >= (NU)(errors->Sup.len)) raiseIndexError();
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(errors->data[((NI) 0)]);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(25, "xmlparser.nim");
	genericSeqAssign((&(*e).errors), errors, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	nimln_(26, "xmlparser.nim");
	raiseException((Exception*)e, "XmlError");
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, add_IfMT5tPSNLKQQespGYVK4gxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* father, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* son) {
	NI T1_;
	nimfr_("add", "xmltree.nim");
	nimln_(125, "xmltree.nim");
	if (!(((2 &(1U<<((NU)((*father).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_2));
	(*father).kU.S2.s = (tySequence_AjV3cEUgs0Y9c7dCt9aItdIA*) incrSeqV2(&((*father).kU.S2.s)->Sup, sizeof(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*));
	T1_ = (*father).kU.S2.s->Sup.len++;
	asgnRefNoCycle((void**) (&(*father).kU.S2.s->data[T1_]), son);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addNode_zyp9bPAuusjaEVd4gOCiNhQ)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* father, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* son) {
	nimfr_("addNode", "xmlparser.nim");
	nimln_(29, "xmlparser.nim");
	{
		nimln_(398, "system.nim");
		nimln_(29, "xmlparser.nim");
		if (!!((son == NIM_NIL))) goto LA3_;
		add_IfMT5tPSNLKQQespGYVK4gxmltree(father, son);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ, kind_N0M9awVoW5JGLxQwzrpfHgAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ result;
	nimfr_("kind", "parsexml.nim");
{	result = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
	nimln_(140, "parsexml.nim");
	result = (*my).kind;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, tag_QtoaNWis79bdA859c6he5fbA_4xmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n) {
	NimStringDesc* result;
	nimfr_("tag", "xmltree.nim");
	result = (NimStringDesc*)0;
	nimln_(115, "xmltree.nim");
	{
		if (!!(((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_4));
	}
	LA3_: ;
	nimln_(116, "xmltree.nim");
	if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_5));
	result = copyString((*n).kU.S2.fTag);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, untilElementEnd_VysJIpEBv2RXMaExkvp9aiQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* x, tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors) {
	nimfr_("untilElementEnd", "xmlparser.nim");
	{
		nimln_(35, "xmlparser.nim");
		while (1) {
			tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ T3_;
			nimln_(36, "xmlparser.nim");
			T3_ = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
			T3_ = kind_N0M9awVoW5JGLxQwzrpfHgAparsexml((&(*x)));
			switch (T3_) {
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 7):
			{
				nimln_(38, "xmlparser.nim");
				{
					NimStringDesc* T11_;
					nimln_(158, "parsexml.nim");
					{
						if (!!(((448 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA9_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_3));
					}
					LA9_: ;
					nimln_(38, "xmlparser.nim");
					T11_ = (NimStringDesc*)0;
					T11_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(result);
					if (!eqStrings((*x).a, T11_)) goto LA12_;
					nimln_(39, "xmlparser.nim");
					next_l7IS2MtBiHyCD179axgTwXw_11(x);
				}
				goto LA5_;
				LA12_: ;
				{
					NimStringDesc* T15_;
					NimStringDesc* T16_;
					NimStringDesc* T17_;
					NI T18_;
					NimStringDesc* T19_;
					nimln_(41, "xmlparser.nim");
					T15_ = (NimStringDesc*)0;
					T16_ = (NimStringDesc*)0;
					T16_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(result);
					T15_ = rawNewString(T16_->Sup.len + 12);
appendString(T15_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_6));
appendString(T15_, T16_);
appendString(T15_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_7));
					T17_ = (NimStringDesc*)0;
					T17_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&(*x)), T15_);
					(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
					T18_ = (*errors)->Sup.len++;
					T19_ = (NimStringDesc*)0;
					T19_ = (*errors)->data[T18_]; (*errors)->data[T18_] = copyStringRC1(T17_);
					if (T19_) nimGCunrefNoCycle(T19_);
				}
				LA5_: ;
				nimln_(43, "xmlparser.nim");
				goto LA1;
			}
			break;
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 1):
			{
				NimStringDesc* T21_;
				NimStringDesc* T22_;
				NimStringDesc* T23_;
				NI T24_;
				NimStringDesc* T25_;
				nimln_(45, "xmlparser.nim");
				T21_ = (NimStringDesc*)0;
				T22_ = (NimStringDesc*)0;
				T22_ = tag_QtoaNWis79bdA859c6he5fbA_4xmltree(result);
				T21_ = rawNewString(T22_->Sup.len + 12);
appendString(T21_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_6));
appendString(T21_, T22_);
appendString(T21_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_7));
				T23_ = (NimStringDesc*)0;
				T23_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&(*x)), T21_);
				(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
				T24_ = (*errors)->Sup.len++;
				T25_ = (NimStringDesc*)0;
				T25_ = (*errors)->data[T24_]; (*errors)->data[T24_] = copyStringRC1(T23_);
				if (T25_) nimGCunrefNoCycle(T25_);
				nimln_(46, "xmlparser.nim");
				goto LA1;
			}
			break;
			default:
			{
				tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* T27_;
				nimln_(48, "xmlparser.nim");
				T27_ = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
				T27_ = parse_1kYxdgK5JgAL5wWwEf3kGw(x, errors);
				addNode_zyp9bPAuusjaEVd4gOCiNhQ(result, T27_);
			}
			break;
			}
		}
	} LA1: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, attrseq__n1dueK1BMvuSCXgFQEIhvwxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n, tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* attr) {
	nimfr_("attrs=", "xmltree.nim");
	nimln_(181, "xmltree.nim");
	{
		if (!!(((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_4));
	}
	LA3_: ;
	if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_10));
	nimln_(182, "xmltree.nim");
	asgnRef((void**) (&(*n).kU.S2.fAttr), attr);
	popFrame();
}

static N_INLINE(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, attrs_2QT0Y19bvocFDK3gux9c644Qxmltree)(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* n) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	nimfr_("attrs", "xmltree.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(176, "xmltree.nim");
	{
		if (!!(((*n).k == ((tyEnum_XmlNodeKind_L9a59cbX9cQkF2r36q7xUnCbg) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_4));
	}
	LA3_: ;
	nimln_(177, "xmltree.nim");
	if (!(((2 &(1U<<((NU)((*n).k)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_10));
	result = (*n).kU.S2.fAttr;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parse_1kYxdgK5JgAL5wWwEf3kGw)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* x, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ T1_;
	nimfr_("parse", "xmlparser.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	nimln_(51, "xmlparser.nim");
	T1_ = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
	T1_ = kind_N0M9awVoW5JGLxQwzrpfHgAparsexml((&(*x)));
	switch (T1_) {
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 4):
	{
		nimln_(53, "xmlparser.nim");
		nimln_(148, "parsexml.nim");
		{
			if (!!(((10268 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA5_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_8));
		}
		LA5_: ;
		result = newComment_XIJqUJEpTq2bai9bulcUi9bg((*x).a);
		nimln_(54, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 2):
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 3):
	{
		nimln_(56, "xmlparser.nim");
		nimln_(148, "parsexml.nim");
		{
			if (!!(((10268 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA10_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_8));
		}
		LA10_: ;
		result = newText_qt1k3g1aYfrKRVDFYKeG3A((*x).a);
		nimln_(57, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 5):
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 13):
	{
		nimln_(60, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0):
	{
		NimStringDesc* T14_;
		NI T15_;
		NimStringDesc* T16_;
		nimln_(62, "xmlparser.nim");
		T14_ = (NimStringDesc*)0;
		T14_ = errorMsg_OuAOoG9bITnB870Ba1n7ysA((&(*x)));
		(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
		T15_ = (*errors)->Sup.len++;
		T16_ = (NimStringDesc*)0;
		T16_ = (*errors)->data[T15_]; (*errors)->data[T15_] = copyStringRC1(T14_);
		if (T16_) nimGCunrefNoCycle(T16_);
		nimln_(63, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 6):
	{
		nimln_(65, "xmlparser.nim");
		nimln_(158, "parsexml.nim");
		{
			if (!!(((448 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA20_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_3));
		}
		LA20_: ;
		result = newElement_uONDNX4Q6ri9c9cSfLIvv8DQ((*x).a);
		nimln_(66, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
		nimln_(67, "xmlparser.nim");
		untilElementEnd_VysJIpEBv2RXMaExkvp9aiQ(x, result, errors);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 7):
	{
		NimStringDesc* T23_;
		NimStringDesc* T28_;
		NI T29_;
		NimStringDesc* T30_;
		nimln_(69, "xmlparser.nim");
		T23_ = (NimStringDesc*)0;
		nimln_(158, "parsexml.nim");
		{
			if (!!(((448 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA26_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_3));
		}
		LA26_: ;
		T23_ = rawNewString((*x).a->Sup.len + 23);
appendString(T23_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_9));
appendString(T23_, (*x).a);
		T28_ = (NimStringDesc*)0;
		T28_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&(*x)), T23_);
		(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
		T29_ = (*errors)->Sup.len++;
		T30_ = (NimStringDesc*)0;
		T30_ = (*errors)->data[T29_]; (*errors)->data[T29_] = copyStringRC1(T28_);
		if (T30_) nimGCunrefNoCycle(T30_);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 8):
	{
		tyArray_9cQD2Rag5wSTKjlY7q5DZNg T36_;
		tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* T37_;
		nimln_(71, "xmlparser.nim");
		nimln_(158, "parsexml.nim");
		{
			if (!!(((448 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA34_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_3));
		}
		LA34_: ;
		result = newElement_uONDNX4Q6ri9c9cSfLIvv8DQ((*x).a);
		nimln_(72, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
		nimln_(73, "xmlparser.nim");
		memset((void*)T36_, 0, sizeof(T36_));
		T37_ = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
		T37_ = nstnewStringTableWithTableConstr(T36_, 0, ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0));
		attrseq__n1dueK1BMvuSCXgFQEIhvwxmltree(result, T37_);
		{
			nimln_(74, "xmlparser.nim");
			while (1) {
				tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ T40_;
				nimln_(75, "xmlparser.nim");
				T40_ = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
				T40_ = kind_N0M9awVoW5JGLxQwzrpfHgAparsexml((&(*x)));
				switch (T40_) {
				case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9):
				{
					tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* T42_;
					nimln_(77, "xmlparser.nim");
					T42_ = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
					T42_ = attrs_2QT0Y19bvocFDK3gux9c644Qxmltree(result);
					nimln_(174, "parsexml.nim");
					{
						if (!!(((*x).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9)))) goto LA45_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_11));
					}
					LA45_: ;
					nimln_(182, "parsexml.nim");
					{
						if (!!(((*x).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9)))) goto LA49_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_11));
					}
					LA49_: ;
					nstPut(T42_, (*x).a, (*x).b);
					nimln_(78, "xmlparser.nim");
					next_l7IS2MtBiHyCD179axgTwXw_11(x);
				}
				break;
				case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 10):
				{
					nimln_(80, "xmlparser.nim");
					next_l7IS2MtBiHyCD179axgTwXw_11(x);
					nimln_(81, "xmlparser.nim");
					goto LA38;
				}
				break;
				case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0):
				{
					NimStringDesc* T53_;
					NI T54_;
					NimStringDesc* T55_;
					nimln_(83, "xmlparser.nim");
					T53_ = (NimStringDesc*)0;
					T53_ = errorMsg_OuAOoG9bITnB870Ba1n7ysA((&(*x)));
					(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
					T54_ = (*errors)->Sup.len++;
					T55_ = (NimStringDesc*)0;
					T55_ = (*errors)->data[T54_]; (*errors)->data[T54_] = copyStringRC1(T53_);
					if (T55_) nimGCunrefNoCycle(T55_);
					nimln_(84, "xmlparser.nim");
					next_l7IS2MtBiHyCD179axgTwXw_11(x);
					nimln_(85, "xmlparser.nim");
					goto LA38;
				}
				break;
				default:
				{
					NimStringDesc* T57_;
					NI T58_;
					NimStringDesc* T59_;
					nimln_(87, "xmlparser.nim");
					T57_ = (NimStringDesc*)0;
					T57_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&(*x)), ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_12));
					(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
					T58_ = (*errors)->Sup.len++;
					T59_ = (NimStringDesc*)0;
					T59_ = (*errors)->data[T58_]; (*errors)->data[T58_] = copyStringRC1(T57_);
					if (T59_) nimGCunrefNoCycle(T59_);
					nimln_(88, "xmlparser.nim");
					next_l7IS2MtBiHyCD179axgTwXw_11(x);
					nimln_(89, "xmlparser.nim");
					goto LA38;
				}
				break;
				}
			}
		} LA38: ;
		nimln_(90, "xmlparser.nim");
		untilElementEnd_VysJIpEBv2RXMaExkvp9aiQ(x, result, errors);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9):
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 10):
	{
		NimStringDesc* T61_;
		NI T62_;
		NimStringDesc* T63_;
		nimln_(92, "xmlparser.nim");
		T61_ = (NimStringDesc*)0;
		T61_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&(*x)), ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_13));
		(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
		T62_ = (*errors)->Sup.len++;
		T63_ = (NimStringDesc*)0;
		T63_ = (*errors)->data[T62_]; (*errors)->data[T62_] = copyStringRC1(T61_);
		if (T63_) nimGCunrefNoCycle(T63_);
		nimln_(93, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 11):
	{
		nimln_(95, "xmlparser.nim");
		nimln_(148, "parsexml.nim");
		{
			if (!!(((10268 &(1U<<((NU)((*x).kind)&15U)))!=0))) goto LA67_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_8));
		}
		LA67_: ;
		result = newCData_WuMZkkUy9cJG3jFSbh019avw((*x).a);
		nimln_(96, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 12):
	{
		nimln_(99, "xmlparser.nim");
		nimln_(166, "parsexml.nim");
		{
			if (!!(((*x).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 12)))) goto LA72_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_14));
		}
		LA72_: ;
		result = newEntity_9ctb9aQYaBwNTYctI3EKuEvQ((*x).a);
		nimln_(100, "xmlparser.nim");
		next_l7IS2MtBiHyCD179axgTwXw_11(x);
	}
	break;
	case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 1):
	{
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, close_Oot2zKx9cpsstnS9bf7hZfVAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsexml.nim");
	nimln_(136, "parsexml.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parseXml_iqQOZrmB4Y9ciOe5n4tpMxw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc* filename, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg x;
	nimfr_("parseXml", "xmlparser.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	memset((void*)(&x), 0, sizeof(x));
	x.Sup.Sup.m_type = (&NTI_AbcNJUHmXZCVg300UxOzLg_);
	nimln_(108, "xmlparser.nim");
	open_V2ukTv2NIJNJ3rLrjojBGA((&x), s, filename, 2);
	{
		nimln_(109, "xmlparser.nim");
		while (1) {
			tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ T3_;
			nimln_(110, "xmlparser.nim");
			next_l7IS2MtBiHyCD179axgTwXw_11((&x));
			nimln_(111, "xmlparser.nim");
			T3_ = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
			T3_ = kind_N0M9awVoW5JGLxQwzrpfHgAparsexml((&x));
			switch (T3_) {
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 8):
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 6):
			{
				nimln_(113, "xmlparser.nim");
				result = parse_1kYxdgK5JgAL5wWwEf3kGw((&x), errors);
				nimln_(114, "xmlparser.nim");
				goto LA1;
			}
			break;
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 4):
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 3):
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 13):
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 5):
			{
			}
			break;
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0):
			{
				NimStringDesc* T7_;
				NI T8_;
				NimStringDesc* T9_;
				nimln_(117, "xmlparser.nim");
				T7_ = (NimStringDesc*)0;
				T7_ = errorMsg_OuAOoG9bITnB870Ba1n7ysA((&x));
				(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
				T8_ = (*errors)->Sup.len++;
				T9_ = (NimStringDesc*)0;
				T9_ = (*errors)->data[T8_]; (*errors)->data[T8_] = copyStringRC1(T7_);
				if (T9_) nimGCunrefNoCycle(T9_);
			}
			break;
			default:
			{
				NimStringDesc* T11_;
				NI T12_;
				NimStringDesc* T13_;
				nimln_(119, "xmlparser.nim");
				T11_ = (NimStringDesc*)0;
				T11_ = errorMsg_YIH03aH6dy2ESIzuZxY0yQ((&x), ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_13));
				(*errors) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*errors))->Sup, sizeof(NimStringDesc*));
				T12_ = (*errors)->Sup.len++;
				T13_ = (NimStringDesc*)0;
				T13_ = (*errors)->data[T12_]; (*errors)->data[T12_] = copyStringRC1(T11_);
				if (T13_) nimGCunrefNoCycle(T13_);
				nimln_(120, "xmlparser.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	nimln_(121, "xmlparser.nim");
	close_Oot2zKx9cpsstnS9bf7hZfVAparsexml((&x));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, parseXml_37vKClm3NqjjKqbh2a689aw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* errors;
	nimfr_("parseXml", "xmlparser.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	nimln_(126, "xmlparser.nim");
	errors = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(127, "xmlparser.nim");
	result = parseXml_iqQOZrmB4Y9ciOe5n4tpMxw(s, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_15), (&errors));
	nimln_(128, "xmlparser.nim");
	{
		NI T3_;
		T3_ = (errors ? errors->Sup.len : 0);
		if (!(((NI) 0) < T3_)) goto LA4_;
		raiseInvalidXml_VMPgMzv9a9bcKoG3r9cZEbEeg(errors);
	}
	LA4_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, loadXml_9aDY8nkp5finOQtxIc7OvpQ)(NimStringDesc* path, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** errors) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* s;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T6_;
	nimfr_("loadXml", "xmlparser.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	nimln_(134, "xmlparser.nim");
	s = newFileStream_9argyMqCIlB1KDaxUuYVcmw(path, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	nimln_(135, "xmlparser.nim");
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(135, "xmlparser.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(path->Sup.len + 21);
appendString(T5_, ((NimStringDesc*) &TM_u0mC1ER8iy09bE9aXHBhXAXw_16));
appendString(T5_, path);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T5_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(135, "xmlparser.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA3_: ;
	nimln_(136, "xmlparser.nim");
	T6_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T6_ = &s->Sup;
	result = parseXml_iqQOZrmB4Y9ciOe5n4tpMxw(T6_, path, errors);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*, loadXml_9a1UKxr09afI9bxerDMiekk9cw)(NimStringDesc* path) {
	tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ* result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* errors;
	nimfr_("loadXml", "xmlparser.nim");
	result = (tyObject_XmlNodeObj_X79bE2j9a1V7tizbx9blALudQ*)0;
	nimln_(142, "xmlparser.nim");
	errors = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(143, "xmlparser.nim");
	result = loadXml_9aDY8nkp5finOQtxIc7OvpQ(path, (&errors));
	nimln_(144, "xmlparser.nim");
	{
		NI T3_;
		T3_ = (errors ? errors->Sup.len : 0);
		if (!(((NI) 0) < T3_)) goto LA4_;
		raiseInvalidXml_VMPgMzv9a9bcKoG3r9cZEbEeg(errors);
	}
	LA4_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_xmlparserInit000)(void) {
	nimfr_("xmlparser", "xmlparser.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_xmlparserDatInit000)(void) {
static TNimNode TM_u0mC1ER8iy09bE9aXHBhXAXw_0[1];
NTI_Bna0dsG6RR1XOB0smpGHtw_.size = sizeof(tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw);
NTI_Bna0dsG6RR1XOB0smpGHtw_.kind = 17;
NTI_Bna0dsG6RR1XOB0smpGHtw_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_u0mC1ER8iy09bE9aXHBhXAXw_0[0].kind = 1;
TM_u0mC1ER8iy09bE9aXHBhXAXw_0[0].offset = offsetof(tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw, errors);
TM_u0mC1ER8iy09bE9aXHBhXAXw_0[0].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_u0mC1ER8iy09bE9aXHBhXAXw_0[0].name = "errors";
NTI_Bna0dsG6RR1XOB0smpGHtw_.node = &TM_u0mC1ER8iy09bE9aXHBhXAXw_0[0];
NTI_skKOuFAXYIMNcqnreZoFeQ_.size = sizeof(tyObject_XmlError_Bna0dsG6RR1XOB0smpGHtw*);
NTI_skKOuFAXYIMNcqnreZoFeQ_.kind = 22;
NTI_skKOuFAXYIMNcqnreZoFeQ_.base = (&NTI_Bna0dsG6RR1XOB0smpGHtw_);
NTI_skKOuFAXYIMNcqnreZoFeQ_.marker = Marker_tyRef_skKOuFAXYIMNcqnreZoFeQ;
}

