/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_parsexml.o /home/dustin/Documents/EpubCLI/src/nimcache/stdlib_parsexml.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_kxJ71Dt4aJfzjsNqIUZGzQ[9];
typedef NU8 tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ;
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ;
typedef NU8 tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw;
typedef NU8 tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg;
struct tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg {
  tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
NimStringDesc* a;
NimStringDesc* b;
NimStringDesc* c;
tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ kind;
tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw err;
tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg state;
NimStringDesc* filename;
tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ options;
};
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NU8 tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ;
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
N_LIB_PRIVATE N_NIMCALL(void, open_V2ukTv2NIJNJ3rLrjojBGA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ options);
N_LIB_PRIVATE N_NIMCALL(void, open_xmgaYJZNnO6QcDtac9bs3Vg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NI bufLen, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, close_Oot2zKx9cpsstnS9bf7hZfVAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
static N_INLINE(tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ, kind_N0M9awVoW5JGLxQwzrpfHgAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NimStringDesc*, rawData_ho4oiGW3L6G9bDenbESLZLwparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NimStringDesc*, rawData2_ho4oiGW3L6G9bDenbESLZLw_2parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NI, getColumn_Y06MNsJIPl6nxL9cfdeEycQparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber_9cj186ckGjLqyndkoW7bBdg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
static N_INLINE(NI, getLine_Y06MNsJIPl6nxL9cfdeEycQ_2parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NimStringDesc*, getFilename_ho4oiGW3L6G9bDenbESLZLw_3parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_OuAOoG9bITnB870Ba1n7ysA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected_WiCdQKYAovIvC8hWPFN63A)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc* tag);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_YIH03aH6dy2ESIzuZxY0yQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc* msg);
static N_INLINE(void, markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw kind);
N_LIB_PRIVATE N_NIMCALL(void, parseCDATA_l7IS2MtBiHyCD179axgTwXw)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR_IwUEvMBOLRY9cqyar6XKEaw_2)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF_IwUEvMBOLRY9cqyar6XKEaw_3)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, parseComment_l7IS2MtBiHyCD179axgTwXw_2)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NIM_BOOL skip);
N_LIB_PRIVATE N_NIMCALL(void, parseName_kIGJiKxQ2Edw7jfIx9aJtbQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc** dest);
N_LIB_PRIVATE N_NIMCALL(void, parseEntity_kIGJiKxQ2Edw7jfIx9aJtbQ_2)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc** dest);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, parsePI_l7IS2MtBiHyCD179axgTwXw_3)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, parseSpecial_l7IS2MtBiHyCD179axgTwXw_4)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, parseTag_l7IS2MtBiHyCD179axgTwXw_5)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, parseEndTag_l7IS2MtBiHyCD179axgTwXw_6)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, parseAttribute_l7IS2MtBiHyCD179axgTwXw_7)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, parseCharData_l7IS2MtBiHyCD179axgTwXw_8)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok_l7IS2MtBiHyCD179axgTwXw_9)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, getTok_l7IS2MtBiHyCD179axgTwXw_10)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
N_LIB_PRIVATE N_NIMCALL(void, next_l7IS2MtBiHyCD179axgTwXw_11)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_B6cGbTPhMsqMovc9cOcIHRw_;
TNimType NTI_AbcNJUHmXZCVg300UxOzLg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_Qknhzh4VTsYTMpU18vpBLQ_;
TNimType NTI_F9abdZJggjbagkcCFgqbI9bw_;
TNimType NTI_W9a0n9bkhFkprfWuBVM2z9bBg_;
TNimType NTI_VCopfBMD18d0QUQlFvdMUQ_;
TNimType NTI_smopboHXIPvj5YRsyy63RA_;
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_2, "no error", 8);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_3, "\']]>\' expected", 14);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_4, "name expected", 13);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_5, "\';\' expected", 12);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_6, "\'\?>\' expected", 13);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_7, "\'>\' expected", 12);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_8, "\'=\' expected", 12);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_9, "\'\"\' or \"\'\" expected", 19);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_10, "\'-->\' expected", 14);
NIM_CONST tyArray_kxJ71Dt4aJfzjsNqIUZGzQ errorMessages_uV6gyZ9cD9b0x7S1f6LY2W3g = {((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_2),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_3),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_4),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_5),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_6),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_7),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_8),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_9),
((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_10)}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_mQUBeySWbTZT1BNx9b2ZGEg_11 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_12, "", 0);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_13, "my.kind == xmlError ", 20);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_14, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_15, "<$1> expected", 13);
NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw NameStartChar_ms9b6oDgoSTfgE9akRmS69b4Q = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw NameChar_hATmu3XTp9abT0O3aohiv9aw = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0xFF, 0x07,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_98, "\012not (my.kind == xmlError) ", 27);
STRING_LITERAL(TM_mQUBeySWbTZT1BNx9b2ZGEg_99, "xml", 3);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, open_V2ukTv2NIJNJ3rLrjojBGA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ options) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("open", "parsexml.nim");
	nimln_(125, "parsexml.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	open_xmgaYJZNnO6QcDtac9bs3Vg(T1_, input, ((NI) 8192), TM_mQUBeySWbTZT1BNx9b2ZGEg_11);
	nimln_(126, "parsexml.nim");
	unsureAsgnRef((void**) (&(*my).filename), copyString(filename));
	nimln_(127, "parsexml.nim");
	(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 0);
	nimln_(128, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0);
	nimln_(129, "parsexml.nim");
	unsureAsgnRef((void**) (&(*my).a), copyString(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_12)));
	nimln_(130, "parsexml.nim");
	unsureAsgnRef((void**) (&(*my).b), copyString(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_12)));
	nimln_(131, "parsexml.nim");
	unsureAsgnRef((void**) (&(*my).c), copyString(NIM_NIL));
	nimln_(132, "parsexml.nim");
	(*my).options = options;
	popFrame();
}

static N_INLINE(void, close_Oot2zKx9cpsstnS9bf7hZfVAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsexml.nim");
	nimln_(136, "parsexml.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

static N_INLINE(tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ, kind_N0M9awVoW5JGLxQwzrpfHgAparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ result;
	nimfr_("kind", "parsexml.nim");
{	result = (tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ)0;
	nimln_(140, "parsexml.nim");
	result = (*my).kind;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, rawData_ho4oiGW3L6G9bDenbESLZLwparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NimStringDesc* result;
	nimfr_("rawData", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(204, "parsexml.nim");
	result = (*my).a;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, rawData2_ho4oiGW3L6G9bDenbESLZLw_2parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NimStringDesc* result;
	nimfr_("rawData2", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(209, "parsexml.nim");
	result = (*my).b;
	popFrame();
	return result;
}

static N_INLINE(NI, getColumn_Y06MNsJIPl6nxL9cfdeEycQparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI result;
	nimfr_("getColumn", "parsexml.nim");
	result = (NI)0;
	nimln_(213, "parsexml.nim");
	result = getColNumber_9cj186ckGjLqyndkoW7bBdg((&(*my).Sup), (*my).Sup.bufpos);
	popFrame();
	return result;
}

static N_INLINE(NI, getLine_Y06MNsJIPl6nxL9cfdeEycQ_2parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI result;
	nimfr_("getLine", "parsexml.nim");
	result = (NI)0;
	nimln_(217, "parsexml.nim");
	result = (*my).Sup.lineNumber;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getFilename_ho4oiGW3L6G9bDenbESLZLw_3parsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NimStringDesc* result;
	nimfr_("getFilename", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(221, "parsexml.nim");
	result = copyString((*my).filename);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_OuAOoG9bITnB870Ba1n7ysA)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NimStringDesc* result;
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T5_;
	NI T6_;
	NI T7_;
	nimfr_("errorMsg", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(225, "parsexml.nim");
	{
		if (!!(((*my).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_13));
	}
	LA3_: ;
	nimln_(226, "parsexml.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T5_[0] = copyString((*my).filename);
	nimln_(227, "parsexml.nim");
	T6_ = (NI)0;
	T6_ = getLine_Y06MNsJIPl6nxL9cfdeEycQ_2parsexml(my);
	T5_[1] = nimIntToStr(T6_);
	T7_ = (NI)0;
	T7_ = getColumn_Y06MNsJIPl6nxL9cfdeEycQparsexml(my);
	T5_[2] = nimIntToStr(T7_);
	T5_[3] = copyString(errorMessages_uV6gyZ9cD9b0x7S1f6LY2W3g[((*my).err)- 0]);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_14), T5_, 4);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected_WiCdQKYAovIvC8hWPFN63A)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc* tag) {
	NimStringDesc* result;
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	nimfr_("errorMsgExpected", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(232, "parsexml.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString((*my).filename);
	nimln_(233, "parsexml.nim");
	T2_ = (NI)0;
	T2_ = getLine_Y06MNsJIPl6nxL9cfdeEycQ_2parsexml(my);
	T1_[1] = nimIntToStr(T2_);
	T3_ = (NI)0;
	T3_ = getColumn_Y06MNsJIPl6nxL9cfdeEycQparsexml(my);
	T1_[2] = nimIntToStr(T3_);
	T1_[3] = nsuFormatSingleElem(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_15), tag);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_14), T1_, 4);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsg_YIH03aH6dy2ESIzuZxY0yQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc* msg) {
	NimStringDesc* result;
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	nimfr_("errorMsg", "parsexml.nim");
	result = (NimStringDesc*)0;
	nimln_(238, "parsexml.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString((*my).filename);
	nimln_(239, "parsexml.nim");
	T2_ = (NI)0;
	T2_ = getLine_Y06MNsJIPl6nxL9cfdeEycQ_2parsexml(my);
	T1_[1] = nimIntToStr(T2_);
	T3_ = (NI)0;
	T3_ = getColumn_Y06MNsJIPl6nxL9cfdeEycQparsexml(my);
	T1_[2] = nimIntToStr(T3_);
	T1_[3] = copyString(msg);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_14), T1_, 4);
	popFrame();
	return result;
}

static N_INLINE(void, markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw kind) {
	nimfr_("markError", "parsexml.nim");
	nimln_(242, "parsexml.nim");
	(*my).err = kind;
	nimln_(243, "parsexml.nim");
	(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 4);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseCDATA_l7IS2MtBiHyCD179axgTwXw)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI pos;
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_16;
	NCSTRING buf;
	nimfr_("parseCDATA", "parsexml.nim");
	nimln_(246, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_16 = addInt((*my).Sup.bufpos, ((NI) 9));
	pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_16);
	nimln_(247, "parsexml.nim");
	buf = (*my).Sup.buf;
	{
		nimln_(248, "parsexml.nim");
		while (1) {
			nimln_(249, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 93:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_20;
				nimln_(251, "parsexml.nim");
				{
					NIM_BOOL T6_;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_17;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_18;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_19;
					T6_ = (NIM_BOOL)0;
					TM_mQUBeySWbTZT1BNx9b2ZGEg_17 = addInt(pos, ((NI) 1));
					T6_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_17)]) == (NU8)(93));
					if (!(T6_)) goto LA7_;
					TM_mQUBeySWbTZT1BNx9b2ZGEg_18 = addInt(pos, ((NI) 2));
					T6_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_18)]) == (NU8)(62));
					LA7_: ;
					if (!T6_) goto LA8_;
					nimln_(252, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_19 = addInt(pos, ((NI) 3));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_19);
					nimln_(253, "parsexml.nim");
					goto LA1;
				}
				LA8_: ;
				nimln_(254, "parsexml.nim");
				(*my).a = addChar((*my).a, 93);
				nimln_(255, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_20 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_20);
			}
			break;
			case 0:
			{
				nimln_(257, "parsexml.nim");
				markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 1));
				nimln_(258, "parsexml.nim");
				goto LA1;
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T12_;
				nimln_(260, "parsexml.nim");
				T12_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T12_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T12_, pos);
				nimln_(261, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(262, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T14_;
				nimln_(264, "parsexml.nim");
				T14_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T14_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T14_, pos);
				nimln_(265, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(266, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 47:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T16_;
				nimln_(268, "parsexml.nim");
				T16_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T16_ = &my->Sup;
				pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T16_, pos);
				nimln_(269, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(270, "parsexml.nim");
				(*my).a = addChar((*my).a, 47);
			}
			break;
			default:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_21;
				nimln_(272, "parsexml.nim");
				(*my).a = addChar((*my).a, buf[pos]);
				nimln_(273, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_21 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_21);
			}
			break;
			}
		}
	} LA1: ;
	nimln_(274, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(275, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 11);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseComment_l7IS2MtBiHyCD179axgTwXw_2)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI pos;
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_22;
	NCSTRING buf;
	nimfr_("parseComment", "parsexml.nim");
	nimln_(278, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_22 = addInt((*my).Sup.bufpos, ((NI) 4));
	pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_22);
	nimln_(279, "parsexml.nim");
	buf = (*my).Sup.buf;
	{
		nimln_(280, "parsexml.nim");
		while (1) {
			nimln_(281, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 45:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_26;
				nimln_(283, "parsexml.nim");
				{
					NIM_BOOL T6_;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_23;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_24;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_25;
					T6_ = (NIM_BOOL)0;
					TM_mQUBeySWbTZT1BNx9b2ZGEg_23 = addInt(pos, ((NI) 1));
					T6_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_23)]) == (NU8)(45));
					if (!(T6_)) goto LA7_;
					TM_mQUBeySWbTZT1BNx9b2ZGEg_24 = addInt(pos, ((NI) 2));
					T6_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_24)]) == (NU8)(62));
					LA7_: ;
					if (!T6_) goto LA8_;
					nimln_(284, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_25 = addInt(pos, ((NI) 3));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_25);
					nimln_(285, "parsexml.nim");
					goto LA1;
				}
				LA8_: ;
				nimln_(286, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA12_;
					(*my).a = addChar((*my).a, 45);
				}
				LA12_: ;
				nimln_(287, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_26 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_26);
			}
			break;
			case 0:
			{
				nimln_(289, "parsexml.nim");
				markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 8));
				nimln_(290, "parsexml.nim");
				goto LA1;
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T16_;
				nimln_(292, "parsexml.nim");
				T16_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T16_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T16_, pos);
				nimln_(293, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(294, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA19_;
					(*my).a = addChar((*my).a, 10);
				}
				LA19_: ;
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T22_;
				nimln_(296, "parsexml.nim");
				T22_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T22_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T22_, pos);
				nimln_(297, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(298, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA25_;
					(*my).a = addChar((*my).a, 10);
				}
				LA25_: ;
			}
			break;
			case 47:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T28_;
				nimln_(300, "parsexml.nim");
				T28_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T28_ = &my->Sup;
				pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T28_, pos);
				nimln_(301, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(302, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA31_;
					(*my).a = addChar((*my).a, 47);
				}
				LA31_: ;
			}
			break;
			default:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_27;
				nimln_(304, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA36_;
					(*my).a = addChar((*my).a, buf[pos]);
				}
				LA36_: ;
				nimln_(305, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_27 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_27);
			}
			break;
			}
		}
	} LA1: ;
	nimln_(306, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(307, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 4);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NIM_BOOL skip) {
	NI pos;
	NCSTRING buf;
	nimfr_("parseWhitespace", "parsexml.nim");
	nimln_(310, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(311, "parsexml.nim");
	buf = (*my).Sup.buf;
	{
		nimln_(312, "parsexml.nim");
		while (1) {
			nimln_(313, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 32:
			case 9:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_28;
				nimln_(315, "parsexml.nim");
				{
					if (!!(skip)) goto LA6_;
					(*my).a = addChar((*my).a, buf[pos]);
				}
				LA6_: ;
				nimln_(316, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_28 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_28);
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T9_;
				nimln_(319, "parsexml.nim");
				T9_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T9_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T9_, pos);
				nimln_(320, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(321, "parsexml.nim");
				{
					if (!!(skip)) goto LA12_;
					(*my).a = addChar((*my).a, 10);
				}
				LA12_: ;
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T15_;
				nimln_(323, "parsexml.nim");
				T15_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T15_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T15_, pos);
				nimln_(324, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(325, "parsexml.nim");
				{
					if (!!(skip)) goto LA18_;
					(*my).a = addChar((*my).a, 10);
				}
				LA18_: ;
			}
			break;
			default:
			{
				nimln_(327, "parsexml.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	nimln_(328, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseName_kIGJiKxQ2Edw7jfIx9aJtbQ)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc** dest) {
	NI pos;
	NCSTRING buf;
	nimfr_("parseName", "parsexml.nim");
	nimln_(335, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(336, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(337, "parsexml.nim");
	{
		if (!(((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) == ((NU8)(95)) || ((NU8)(buf[pos])) == ((NU8)(58)) || ((NU8)(buf[pos])) >= ((NU8)(128)) && ((NU8)(buf[pos])) <= ((NU8)(255)))) goto LA3_;
		{
			nimln_(338, "parsexml.nim");
			while (1) {
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_29;
				nimln_(339, "parsexml.nim");
				(*dest) = addChar((*dest), buf[pos]);
				nimln_(340, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_29 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_29);
				nimln_(341, "parsexml.nim");
				{
					nimln_(1212, "system.nim");
					nimln_(341, "parsexml.nim");
					if (!!((((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)) || ((NU8)(buf[pos])) == ((NU8)(46)) || ((NU8)(buf[pos])) == ((NU8)(45)) || ((NU8)(buf[pos])) == ((NU8)(95)) || ((NU8)(buf[pos])) == ((NU8)(58)) || ((NU8)(buf[pos])) >= ((NU8)(128)) && ((NU8)(buf[pos])) <= ((NU8)(255))))) goto LA9_;
					goto LA5;
				}
				LA9_: ;
			}
		} LA5: ;
		nimln_(342, "parsexml.nim");
		(*my).Sup.bufpos = pos;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(344, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 2));
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, parseEntity_kIGJiKxQ2Edw7jfIx9aJtbQ_2)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my, NimStringDesc** dest) {
	NI pos;
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_30;
	NCSTRING buf;
	nimfr_("parseEntity", "parsexml.nim");
	nimln_(347, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_30 = addInt((*my).Sup.bufpos, ((NI) 1));
	pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_30);
	nimln_(348, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(349, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 2);
	nimln_(350, "parsexml.nim");
	{
		NI r;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_31;
		NimStringDesc* T18_;
		if (!((NU8)(buf[pos]) == (NU8)(35))) goto LA3_;
		r = (NI)0;
		nimln_(352, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_31 = addInt(pos, ((NI) 1));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_31);
		nimln_(353, "parsexml.nim");
		{
			NI TM_mQUBeySWbTZT1BNx9b2ZGEg_32;
			if (!((NU8)(buf[pos]) == (NU8)(120))) goto LA7_;
			nimln_(354, "parsexml.nim");
			TM_mQUBeySWbTZT1BNx9b2ZGEg_32 = addInt(pos, ((NI) 1));
			pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_32);
			{
				nimln_(355, "parsexml.nim");
				while (1) {
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_38;
					nimln_(356, "parsexml.nim");
					switch (((NU8)(buf[pos]))) {
					case 48 ... 57:
					{
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_33;
						nimln_(357, "parsexml.nim");
						TM_mQUBeySWbTZT1BNx9b2ZGEg_33 = subInt(((NU8)(buf[pos])), ((NI) 48));
						r = (NI)((NI)((NU64)(r) << (NU64)(((NI) 4))) | (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_33));
					}
					break;
					case 97 ... 102:
					{
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_34;
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_35;
						nimln_(358, "parsexml.nim");
						TM_mQUBeySWbTZT1BNx9b2ZGEg_34 = subInt(((NU8)(buf[pos])), ((NI) 97));
						TM_mQUBeySWbTZT1BNx9b2ZGEg_35 = addInt((NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_34), ((NI) 10));
						r = (NI)((NI)((NU64)(r) << (NU64)(((NI) 4))) | (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_35));
					}
					break;
					case 65 ... 70:
					{
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_36;
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_37;
						nimln_(359, "parsexml.nim");
						TM_mQUBeySWbTZT1BNx9b2ZGEg_36 = subInt(((NU8)(buf[pos])), ((NI) 65));
						TM_mQUBeySWbTZT1BNx9b2ZGEg_37 = addInt((NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_36), ((NI) 10));
						r = (NI)((NI)((NU64)(r) << (NU64)(((NI) 4))) | (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_37));
					}
					break;
					default:
					{
						nimln_(360, "parsexml.nim");
						goto LA9;
					}
					break;
					}
					nimln_(361, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_38 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_38);
				}
			} LA9: ;
		}
		goto LA5_;
		LA7_: ;
		{
			{
				nimln_(363, "parsexml.nim");
				while (1) {
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_39;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_40;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_41;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_42;
					if (!(((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)))) goto LA17;
					nimln_(364, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_39 = mulInt(r, ((NI) 10));
					TM_mQUBeySWbTZT1BNx9b2ZGEg_40 = subInt(((NU8)(buf[pos])), ((NI) 48));
					TM_mQUBeySWbTZT1BNx9b2ZGEg_41 = addInt((NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_39), (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_40));
					r = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_41);
					nimln_(365, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_42 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_42);
				} LA17: ;
			}
		}
		LA5_: ;
		nimln_(366, "parsexml.nim");
		T18_ = (NimStringDesc*)0;
		T18_ = nuctoUTF8(((NI32)chckRange(r, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
		(*dest) = resizeString((*dest), T18_->Sup.len + 0);
appendString((*dest), T18_);
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T20_;
		NIM_BOOL T21_;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_43;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_44;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_45;
		nimln_(367, "parsexml.nim");
		T20_ = (NIM_BOOL)0;
		T21_ = (NIM_BOOL)0;
		T21_ = ((NU8)(buf[pos]) == (NU8)(108));
		if (!(T21_)) goto LA22_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_43 = addInt(pos, ((NI) 1));
		T21_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_43)]) == (NU8)(116));
		LA22_: ;
		T20_ = T21_;
		if (!(T20_)) goto LA23_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_44 = addInt(pos, ((NI) 2));
		T20_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_44)]) == (NU8)(59));
		LA23_: ;
		if (!T20_) goto LA24_;
		nimln_(368, "parsexml.nim");
		(*dest) = addChar((*dest), 60);
		nimln_(369, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_45 = addInt(pos, ((NI) 2));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_45);
	}
	goto LA1_;
	LA24_: ;
	{
		NIM_BOOL T27_;
		NIM_BOOL T28_;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_46;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_47;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_48;
		nimln_(370, "parsexml.nim");
		T27_ = (NIM_BOOL)0;
		T28_ = (NIM_BOOL)0;
		T28_ = ((NU8)(buf[pos]) == (NU8)(103));
		if (!(T28_)) goto LA29_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_46 = addInt(pos, ((NI) 1));
		T28_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_46)]) == (NU8)(116));
		LA29_: ;
		T27_ = T28_;
		if (!(T27_)) goto LA30_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_47 = addInt(pos, ((NI) 2));
		T27_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_47)]) == (NU8)(59));
		LA30_: ;
		if (!T27_) goto LA31_;
		nimln_(371, "parsexml.nim");
		(*dest) = addChar((*dest), 62);
		nimln_(372, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_48 = addInt(pos, ((NI) 2));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_48);
	}
	goto LA1_;
	LA31_: ;
	{
		NIM_BOOL T34_;
		NIM_BOOL T35_;
		NIM_BOOL T36_;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_49;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_50;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_51;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_52;
		nimln_(373, "parsexml.nim");
		T34_ = (NIM_BOOL)0;
		T35_ = (NIM_BOOL)0;
		T36_ = (NIM_BOOL)0;
		T36_ = ((NU8)(buf[pos]) == (NU8)(97));
		if (!(T36_)) goto LA37_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_49 = addInt(pos, ((NI) 1));
		T36_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_49)]) == (NU8)(109));
		LA37_: ;
		T35_ = T36_;
		if (!(T35_)) goto LA38_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_50 = addInt(pos, ((NI) 2));
		T35_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_50)]) == (NU8)(112));
		LA38_: ;
		T34_ = T35_;
		if (!(T34_)) goto LA39_;
		nimln_(374, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_51 = addInt(pos, ((NI) 3));
		T34_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_51)]) == (NU8)(59));
		LA39_: ;
		if (!T34_) goto LA40_;
		nimln_(375, "parsexml.nim");
		(*dest) = addChar((*dest), 38);
		nimln_(376, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_52 = addInt(pos, ((NI) 3));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_52);
	}
	goto LA1_;
	LA40_: ;
	{
		NIM_BOOL T43_;
		NIM_BOOL T44_;
		NIM_BOOL T45_;
		NIM_BOOL T46_;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_53;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_54;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_55;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_56;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_57;
		nimln_(377, "parsexml.nim");
		T43_ = (NIM_BOOL)0;
		T44_ = (NIM_BOOL)0;
		T45_ = (NIM_BOOL)0;
		T46_ = (NIM_BOOL)0;
		T46_ = ((NU8)(buf[pos]) == (NU8)(97));
		if (!(T46_)) goto LA47_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_53 = addInt(pos, ((NI) 1));
		T46_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_53)]) == (NU8)(112));
		LA47_: ;
		T45_ = T46_;
		if (!(T45_)) goto LA48_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_54 = addInt(pos, ((NI) 2));
		T45_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_54)]) == (NU8)(111));
		LA48_: ;
		T44_ = T45_;
		if (!(T44_)) goto LA49_;
		nimln_(378, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_55 = addInt(pos, ((NI) 3));
		T44_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_55)]) == (NU8)(115));
		LA49_: ;
		T43_ = T44_;
		if (!(T43_)) goto LA50_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_56 = addInt(pos, ((NI) 4));
		T43_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_56)]) == (NU8)(59));
		LA50_: ;
		if (!T43_) goto LA51_;
		nimln_(379, "parsexml.nim");
		(*dest) = addChar((*dest), 39);
		nimln_(380, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_57 = addInt(pos, ((NI) 4));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_57);
	}
	goto LA1_;
	LA51_: ;
	{
		NIM_BOOL T54_;
		NIM_BOOL T55_;
		NIM_BOOL T56_;
		NIM_BOOL T57_;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_58;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_59;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_60;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_61;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_62;
		nimln_(381, "parsexml.nim");
		T54_ = (NIM_BOOL)0;
		T55_ = (NIM_BOOL)0;
		T56_ = (NIM_BOOL)0;
		T57_ = (NIM_BOOL)0;
		T57_ = ((NU8)(buf[pos]) == (NU8)(113));
		if (!(T57_)) goto LA58_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_58 = addInt(pos, ((NI) 1));
		T57_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_58)]) == (NU8)(117));
		LA58_: ;
		T56_ = T57_;
		if (!(T56_)) goto LA59_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_59 = addInt(pos, ((NI) 2));
		T56_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_59)]) == (NU8)(111));
		LA59_: ;
		T55_ = T56_;
		if (!(T55_)) goto LA60_;
		nimln_(382, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_60 = addInt(pos, ((NI) 3));
		T55_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_60)]) == (NU8)(116));
		LA60_: ;
		T54_ = T55_;
		if (!(T54_)) goto LA61_;
		TM_mQUBeySWbTZT1BNx9b2ZGEg_61 = addInt(pos, ((NI) 4));
		T54_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_61)]) == (NU8)(59));
		LA61_: ;
		if (!T54_) goto LA62_;
		nimln_(383, "parsexml.nim");
		(*dest) = addChar((*dest), 34);
		nimln_(384, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_62 = addInt(pos, ((NI) 4));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_62);
	}
	goto LA1_;
	LA62_: ;
	{
		nimln_(386, "parsexml.nim");
		(*my).Sup.bufpos = pos;
		nimln_(387, "parsexml.nim");
		parseName_kIGJiKxQ2Edw7jfIx9aJtbQ(my, dest);
		nimln_(388, "parsexml.nim");
		pos = (*my).Sup.bufpos;
		nimln_(389, "parsexml.nim");
		{
			nimln_(398, "system.nim");
			nimln_(389, "parsexml.nim");
			if (!!(((*my).err == ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 2)))) goto LA67_;
			nimln_(390, "parsexml.nim");
			(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 12);
		}
		goto LA65_;
		LA67_: ;
		{
			nimln_(392, "parsexml.nim");
			(*dest) = addChar((*dest), 38);
		}
		LA65_: ;
	}
	LA1_: ;
	nimln_(393, "parsexml.nim");
	{
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_63;
		if (!((NU8)(buf[pos]) == (NU8)(59))) goto LA72_;
		nimln_(394, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_63 = addInt(pos, ((NI) 1));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_63);
	}
	goto LA70_;
	LA72_: ;
	{
		nimln_(396, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 3));
	}
	LA70_: ;
	nimln_(397, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parsePI_l7IS2MtBiHyCD179axgTwXw_3)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_64;
	NI pos;
	NCSTRING buf;
	nimfr_("parsePI", "parsexml.nim");
	nimln_(400, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_64 = addInt((*my).Sup.bufpos, ((NI) 2));
	(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_64);
	nimln_(401, "parsexml.nim");
	parseName_kIGJiKxQ2Edw7jfIx9aJtbQ(my, (&(*my).a));
	nimln_(402, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(403, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(404, "parsexml.nim");
	(*my).b = setLengthStr((*my).b, ((NI) 0));
	{
		nimln_(405, "parsexml.nim");
		while (1) {
			nimln_(406, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 0:
			{
				nimln_(408, "parsexml.nim");
				markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 4));
				nimln_(409, "parsexml.nim");
				goto LA1;
			}
			break;
			case 63:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_67;
				nimln_(411, "parsexml.nim");
				{
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_65;
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_66;
					TM_mQUBeySWbTZT1BNx9b2ZGEg_65 = addInt(pos, ((NI) 1));
					if (!((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_65)]) == (NU8)(62))) goto LA7_;
					nimln_(412, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_66 = addInt(pos, ((NI) 2));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_66);
					nimln_(413, "parsexml.nim");
					goto LA1;
				}
				LA7_: ;
				nimln_(414, "parsexml.nim");
				(*my).b = addChar((*my).b, 63);
				nimln_(415, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_67 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_67);
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T10_;
				nimln_(418, "parsexml.nim");
				T10_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T10_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T10_, pos);
				nimln_(419, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(420, "parsexml.nim");
				(*my).b = addChar((*my).b, 10);
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T12_;
				nimln_(422, "parsexml.nim");
				T12_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T12_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T12_, pos);
				nimln_(423, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(424, "parsexml.nim");
				(*my).b = addChar((*my).b, 10);
			}
			break;
			case 47:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T14_;
				nimln_(426, "parsexml.nim");
				T14_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T14_ = &my->Sup;
				pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T14_, pos);
				nimln_(427, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(428, "parsexml.nim");
				(*my).b = addChar((*my).b, 47);
			}
			break;
			default:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_68;
				nimln_(430, "parsexml.nim");
				(*my).b = addChar((*my).b, buf[pos]);
				nimln_(431, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_68 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_68);
			}
			break;
			}
		}
	} LA1: ;
	nimln_(432, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(433, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 5);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseSpecial_l7IS2MtBiHyCD179axgTwXw_4)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI pos;
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_69;
	NCSTRING buf;
	NI opentags;
	nimfr_("parseSpecial", "parsexml.nim");
	nimln_(437, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_69 = addInt((*my).Sup.bufpos, ((NI) 2));
	pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_69);
	nimln_(438, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(439, "parsexml.nim");
	opentags = ((NI) 0);
	{
		nimln_(440, "parsexml.nim");
		while (1) {
			nimln_(441, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 0:
			{
				nimln_(443, "parsexml.nim");
				markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 5));
				nimln_(444, "parsexml.nim");
				goto LA1;
			}
			break;
			case 60:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_70;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_71;
				nimln_(446, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_70 = addInt(opentags, ((NI) 1));
				opentags = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_70);
				nimln_(447, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_71 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_71);
				nimln_(448, "parsexml.nim");
				(*my).a = addChar((*my).a, 60);
			}
			break;
			case 62:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_73;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_74;
				nimln_(450, "parsexml.nim");
				{
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_72;
					if (!(opentags <= ((NI) 0))) goto LA8_;
					nimln_(451, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_72 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_72);
					nimln_(452, "parsexml.nim");
					goto LA1;
				}
				LA8_: ;
				nimln_(453, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_73 = subInt(opentags, ((NI) 1));
				opentags = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_73);
				nimln_(454, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_74 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_74);
				nimln_(455, "parsexml.nim");
				(*my).a = addChar((*my).a, 62);
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T11_;
				nimln_(457, "parsexml.nim");
				T11_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T11_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T11_, pos);
				nimln_(458, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(459, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T13_;
				nimln_(461, "parsexml.nim");
				T13_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T13_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T13_, pos);
				nimln_(462, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(463, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 47:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T15_;
				nimln_(465, "parsexml.nim");
				T15_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T15_ = &my->Sup;
				pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T15_, pos);
				nimln_(466, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(467, "parsexml.nim");
				(*my).b = addChar((*my).b, 47);
			}
			break;
			default:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_75;
				nimln_(469, "parsexml.nim");
				(*my).a = addChar((*my).a, buf[pos]);
				nimln_(470, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_75 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_75);
			}
			break;
			}
		}
	} LA1: ;
	nimln_(471, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(472, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 13);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseTag_l7IS2MtBiHyCD179axgTwXw_5)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_76;
	nimfr_("parseTag", "parsexml.nim");
{	nimln_(475, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_76 = addInt((*my).Sup.bufpos, ((NI) 1));
	(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_76);
	nimln_(476, "parsexml.nim");
	parseName_kIGJiKxQ2Edw7jfIx9aJtbQ(my, (&(*my).a));
	nimln_(478, "parsexml.nim");
	{
		if (!(((*my).a ? (*my).a->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(479, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 2);
		nimln_(480, "parsexml.nim");
		(*my).a = addChar((*my).a, 60);
		nimln_(481, "parsexml.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(482, "parsexml.nim");
	parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_TRUE);
	nimln_(483, "parsexml.nim");
	{
		if (!(((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) >= ((NU8)(65)) && ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) <= ((NU8)(90)) || ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) >= ((NU8)(97)) && ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) <= ((NU8)(122)) || ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) == ((NU8)(95)) || ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) == ((NU8)(58)) || ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) >= ((NU8)(128)) && ((NU8)((*my).Sup.buf[(*my).Sup.bufpos])) <= ((NU8)(255)))) goto LA7_;
		nimln_(485, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 8);
		nimln_(486, "parsexml.nim");
		(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 2);
		nimln_(487, "parsexml.nim");
		unsureAsgnRef((void**) (&(*my).c), copyString((*my).a));
	}
	goto LA5_;
	LA7_: ;
	{
		NIM_BOOL slash;
		nimln_(489, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 6);
		nimln_(490, "parsexml.nim");
		slash = ((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(47));
		nimln_(491, "parsexml.nim");
		{
			tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T14_;
			if (!slash) goto LA12_;
			nimln_(492, "parsexml.nim");
			T14_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
			T14_ = &my->Sup;
			(*my).Sup.bufpos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T14_, (*my).Sup.bufpos);
		}
		LA12_: ;
		nimln_(493, "parsexml.nim");
		{
			NIM_BOOL T17_;
			NI TM_mQUBeySWbTZT1BNx9b2ZGEg_77;
			T17_ = (NIM_BOOL)0;
			T17_ = slash;
			if (!(T17_)) goto LA18_;
			T17_ = ((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(62));
			LA18_: ;
			if (!T17_) goto LA19_;
			nimln_(494, "parsexml.nim");
			TM_mQUBeySWbTZT1BNx9b2ZGEg_77 = addInt((*my).Sup.bufpos, ((NI) 1));
			(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_77);
			nimln_(495, "parsexml.nim");
			(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 3);
			nimln_(496, "parsexml.nim");
			unsureAsgnRef((void**) (&(*my).c), copyString(NIM_NIL));
		}
		goto LA15_;
		LA19_: ;
		{
			NI TM_mQUBeySWbTZT1BNx9b2ZGEg_78;
			nimln_(497, "parsexml.nim");
			if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(62))) goto LA22_;
			nimln_(498, "parsexml.nim");
			TM_mQUBeySWbTZT1BNx9b2ZGEg_78 = addInt((*my).Sup.bufpos, ((NI) 1));
			(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_78);
		}
		goto LA15_;
		LA22_: ;
		{
			nimln_(500, "parsexml.nim");
			markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 5));
		}
		LA15_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseEndTag_l7IS2MtBiHyCD179axgTwXw_6)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_79;
	nimfr_("parseEndTag", "parsexml.nim");
	nimln_(503, "parsexml.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	TM_mQUBeySWbTZT1BNx9b2ZGEg_79 = addInt((*my).Sup.bufpos, ((NI) 1));
	(*my).Sup.bufpos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T1_, (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_79));
	nimln_(505, "parsexml.nim");
	parseName_kIGJiKxQ2Edw7jfIx9aJtbQ(my, (&(*my).a));
	nimln_(506, "parsexml.nim");
	parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_TRUE);
	nimln_(507, "parsexml.nim");
	{
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_80;
		if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(62))) goto LA4_;
		nimln_(508, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_80 = addInt((*my).Sup.bufpos, ((NI) 1));
		(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_80);
	}
	goto LA2_;
	LA4_: ;
	{
		nimln_(510, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 5));
	}
	LA2_: ;
	nimln_(511, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 7);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseAttribute_l7IS2MtBiHyCD179axgTwXw_7)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI TM_mQUBeySWbTZT1BNx9b2ZGEg_81;
	NI pos;
	NCSTRING buf;
	nimfr_("parseAttribute", "parsexml.nim");
{	nimln_(514, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9);
	nimln_(515, "parsexml.nim");
	(*my).a = setLengthStr((*my).a, ((NI) 0));
	nimln_(516, "parsexml.nim");
	(*my).b = setLengthStr((*my).b, ((NI) 0));
	nimln_(517, "parsexml.nim");
	parseName_kIGJiKxQ2Edw7jfIx9aJtbQ(my, (&(*my).a));
	nimln_(519, "parsexml.nim");
	{
		if (!(((*my).a ? (*my).a->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(520, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 5));
		nimln_(521, "parsexml.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(522, "parsexml.nim");
	parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_TRUE);
	nimln_(523, "parsexml.nim");
	{
		nimln_(398, "system.nim");
		nimln_(523, "parsexml.nim");
		if (!!(((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(61)))) goto LA7_;
		nimln_(524, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 6));
		nimln_(525, "parsexml.nim");
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(526, "parsexml.nim");
	TM_mQUBeySWbTZT1BNx9b2ZGEg_81 = addInt((*my).Sup.bufpos, ((NI) 1));
	(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_81);
	nimln_(527, "parsexml.nim");
	parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_TRUE);
	nimln_(529, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(530, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(531, "parsexml.nim");
	{
		NIM_CHAR quote;
		NIM_BOOL pendingSpace;
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_82;
		if (!(((NU8)(buf[pos])) == ((NU8)(39)) || ((NU8)(buf[pos])) == ((NU8)(34)))) goto LA11_;
		nimln_(532, "parsexml.nim");
		quote = buf[pos];
		nimln_(533, "parsexml.nim");
		pendingSpace = NIM_FALSE;
		nimln_(534, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_82 = addInt(pos, ((NI) 1));
		pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_82);
		{
			nimln_(535, "parsexml.nim");
			while (1) {
				nimln_(536, "parsexml.nim");
				switch (((NU8)(buf[pos]))) {
				case 0:
				{
					nimln_(538, "parsexml.nim");
					markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 7));
					nimln_(539, "parsexml.nim");
					goto LA13;
				}
				break;
				case 38:
				{
					nimln_(541, "parsexml.nim");
					{
						if (!pendingSpace) goto LA19_;
						nimln_(542, "parsexml.nim");
						(*my).b = addChar((*my).b, 32);
						nimln_(543, "parsexml.nim");
						pendingSpace = NIM_FALSE;
					}
					LA19_: ;
					nimln_(544, "parsexml.nim");
					(*my).Sup.bufpos = pos;
					nimln_(545, "parsexml.nim");
					parseEntity_kIGJiKxQ2Edw7jfIx9aJtbQ_2(my, (&(*my).b));
					nimln_(546, "parsexml.nim");
					(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 9);
					nimln_(547, "parsexml.nim");
					pos = (*my).Sup.bufpos;
				}
				break;
				case 32:
				case 9:
				{
					NI TM_mQUBeySWbTZT1BNx9b2ZGEg_83;
					nimln_(549, "parsexml.nim");
					pendingSpace = NIM_TRUE;
					nimln_(550, "parsexml.nim");
					TM_mQUBeySWbTZT1BNx9b2ZGEg_83 = addInt(pos, ((NI) 1));
					pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_83);
				}
				break;
				case 13:
				{
					tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T23_;
					nimln_(552, "parsexml.nim");
					T23_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
					T23_ = &my->Sup;
					pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T23_, pos);
					nimln_(553, "parsexml.nim");
					buf = (*my).Sup.buf;
					nimln_(554, "parsexml.nim");
					pendingSpace = NIM_TRUE;
				}
				break;
				case 10:
				{
					tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T25_;
					nimln_(556, "parsexml.nim");
					T25_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
					T25_ = &my->Sup;
					pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T25_, pos);
					nimln_(557, "parsexml.nim");
					buf = (*my).Sup.buf;
					nimln_(558, "parsexml.nim");
					pendingSpace = NIM_TRUE;
				}
				break;
				case 47:
				{
					tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T27_;
					nimln_(560, "parsexml.nim");
					T27_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
					T27_ = &my->Sup;
					pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T27_, pos);
					nimln_(561, "parsexml.nim");
					buf = (*my).Sup.buf;
					nimln_(562, "parsexml.nim");
					(*my).b = addChar((*my).b, 47);
				}
				break;
				default:
				{
					nimln_(564, "parsexml.nim");
					{
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_84;
						if (!((NU8)(buf[pos]) == (NU8)(quote))) goto LA31_;
						nimln_(565, "parsexml.nim");
						TM_mQUBeySWbTZT1BNx9b2ZGEg_84 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_84);
						nimln_(566, "parsexml.nim");
						goto LA13;
					}
					goto LA29_;
					LA31_: ;
					{
						NI TM_mQUBeySWbTZT1BNx9b2ZGEg_85;
						nimln_(568, "parsexml.nim");
						{
							if (!pendingSpace) goto LA36_;
							nimln_(569, "parsexml.nim");
							(*my).b = addChar((*my).b, 32);
							nimln_(570, "parsexml.nim");
							pendingSpace = NIM_FALSE;
						}
						LA36_: ;
						nimln_(571, "parsexml.nim");
						(*my).b = addChar((*my).b, buf[pos]);
						nimln_(572, "parsexml.nim");
						TM_mQUBeySWbTZT1BNx9b2ZGEg_85 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_85);
					}
					LA29_: ;
				}
				break;
				}
			}
		} LA13: ;
	}
	goto LA9_;
	LA11_: ;
	{
		nimln_(574, "parsexml.nim");
		markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 7));
		{
			nimln_(576, "parsexml.nim");
			while (1) {
				NIM_BOOL T41_;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_86;
				T41_ = (NIM_BOOL)0;
				nimln_(398, "system.nim");
				nimln_(576, "parsexml.nim");
				T41_ = !(((NU8)(buf[pos]) == (NU8)(62)));
				if (!(T41_)) goto LA42_;
				T41_ = ((NU8)(32) < (NU8)(buf[pos]));
				LA42_: ;
				if (!T41_) goto LA40;
				nimln_(577, "parsexml.nim");
				(*my).b = addChar((*my).b, buf[pos]);
				nimln_(578, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_86 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_86);
			} LA40: ;
		}
	}
	LA9_: ;
	nimln_(579, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(580, "parsexml.nim");
	parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_TRUE);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseCharData_l7IS2MtBiHyCD179axgTwXw_8)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI pos;
	NCSTRING buf;
	nimfr_("parseCharData", "parsexml.nim");
	nimln_(583, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(584, "parsexml.nim");
	buf = (*my).Sup.buf;
	{
		nimln_(585, "parsexml.nim");
		while (1) {
			nimln_(586, "parsexml.nim");
			switch (((NU8)(buf[pos]))) {
			case 0:
			case 60:
			case 38:
			{
				nimln_(587, "parsexml.nim");
				goto LA1;
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T5_;
				nimln_(590, "parsexml.nim");
				T5_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T5_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T5_, pos);
				nimln_(591, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(592, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T7_;
				nimln_(594, "parsexml.nim");
				T7_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T7_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T7_, pos);
				nimln_(595, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(596, "parsexml.nim");
				(*my).a = addChar((*my).a, 10);
			}
			break;
			case 47:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T9_;
				nimln_(598, "parsexml.nim");
				T9_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T9_ = &my->Sup;
				pos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T9_, pos);
				nimln_(599, "parsexml.nim");
				buf = (*my).Sup.buf;
				nimln_(600, "parsexml.nim");
				(*my).a = addChar((*my).a, 47);
			}
			break;
			default:
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_87;
				nimln_(602, "parsexml.nim");
				(*my).a = addChar((*my).a, buf[pos]);
				nimln_(603, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_87 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_87);
			}
			break;
			}
		}
	} LA1: ;
	nimln_(604, "parsexml.nim");
	(*my).Sup.bufpos = pos;
	nimln_(605, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 2);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawGetTok_l7IS2MtBiHyCD179axgTwXw_9)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	NI pos;
	NCSTRING buf;
	nimfr_("rawGetTok", "parsexml.nim");
	nimln_(608, "parsexml.nim");
	(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0);
	nimln_(609, "parsexml.nim");
	(*my).a = setLengthStr((*my).a, ((NI) 0));
	nimln_(610, "parsexml.nim");
	pos = (*my).Sup.bufpos;
	nimln_(611, "parsexml.nim");
	buf = (*my).Sup.buf;
	nimln_(612, "parsexml.nim");
	switch (((NU8)(buf[pos]))) {
	case 60:
	{
		NI TM_mQUBeySWbTZT1BNx9b2ZGEg_88;
		nimln_(614, "parsexml.nim");
		TM_mQUBeySWbTZT1BNx9b2ZGEg_88 = addInt(pos, ((NI) 1));
		switch (((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_88)]))) {
		case 47:
		{
			nimln_(616, "parsexml.nim");
			parseEndTag_l7IS2MtBiHyCD179axgTwXw_6(my);
		}
		break;
		case 33:
		{
			nimln_(618, "parsexml.nim");
			{
				NIM_BOOL T6_;
				NIM_BOOL T7_;
				NIM_BOOL T8_;
				NIM_BOOL T9_;
				NIM_BOOL T10_;
				NIM_BOOL T11_;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_89;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_90;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_91;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_92;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_93;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_94;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_95;
				nimln_(619, "parsexml.nim");
				T6_ = (NIM_BOOL)0;
				T7_ = (NIM_BOOL)0;
				nimln_(618, "parsexml.nim");
				T8_ = (NIM_BOOL)0;
				T9_ = (NIM_BOOL)0;
				T10_ = (NIM_BOOL)0;
				T11_ = (NIM_BOOL)0;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_89 = addInt(pos, ((NI) 2));
				T11_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_89)]) == (NU8)(91));
				if (!(T11_)) goto LA12_;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_90 = addInt(pos, ((NI) 3));
				T11_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_90)]) == (NU8)(67));
				LA12_: ;
				T10_ = T11_;
				if (!(T10_)) goto LA13_;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_91 = addInt(pos, ((NI) 4));
				T10_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_91)]) == (NU8)(68));
				LA13_: ;
				T9_ = T10_;
				if (!(T9_)) goto LA14_;
				nimln_(619, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_92 = addInt(pos, ((NI) 5));
				T9_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_92)]) == (NU8)(65));
				LA14_: ;
				T8_ = T9_;
				if (!(T8_)) goto LA15_;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_93 = addInt(pos, ((NI) 6));
				T8_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_93)]) == (NU8)(84));
				LA15_: ;
				T7_ = T8_;
				if (!(T7_)) goto LA16_;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_94 = addInt(pos, ((NI) 7));
				T7_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_94)]) == (NU8)(65));
				LA16_: ;
				T6_ = T7_;
				if (!(T6_)) goto LA17_;
				nimln_(620, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_95 = addInt(pos, ((NI) 8));
				T6_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_95)]) == (NU8)(91));
				LA17_: ;
				if (!T6_) goto LA18_;
				nimln_(621, "parsexml.nim");
				parseCDATA_l7IS2MtBiHyCD179axgTwXw(my);
			}
			goto LA4_;
			LA18_: ;
			{
				NIM_BOOL T21_;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_96;
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_97;
				nimln_(622, "parsexml.nim");
				T21_ = (NIM_BOOL)0;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_96 = addInt(pos, ((NI) 2));
				T21_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_96)]) == (NU8)(45));
				if (!(T21_)) goto LA22_;
				TM_mQUBeySWbTZT1BNx9b2ZGEg_97 = addInt(pos, ((NI) 3));
				T21_ = ((NU8)(buf[(NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_97)]) == (NU8)(45));
				LA22_: ;
				if (!T21_) goto LA23_;
				nimln_(623, "parsexml.nim");
				parseComment_l7IS2MtBiHyCD179axgTwXw_2(my);
			}
			goto LA4_;
			LA23_: ;
			{
				nimln_(625, "parsexml.nim");
				parseSpecial_l7IS2MtBiHyCD179axgTwXw_4(my);
			}
			LA4_: ;
		}
		break;
		case 63:
		{
			nimln_(627, "parsexml.nim");
			parsePI_l7IS2MtBiHyCD179axgTwXw_3(my);
		}
		break;
		default:
		{
			nimln_(629, "parsexml.nim");
			parseTag_l7IS2MtBiHyCD179axgTwXw_5(my);
		}
		break;
		}
	}
	break;
	case 32:
	case 9:
	case 13:
	case 10:
	{
		nimln_(631, "parsexml.nim");
		parseWhitespace_qVQTq9bOvU7aAwXvE1t2QsQ(my, NIM_FALSE);
		nimln_(632, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 3);
	}
	break;
	case 0:
	{
		nimln_(634, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 1);
	}
	break;
	case 38:
	{
		nimln_(636, "parsexml.nim");
		parseEntity_kIGJiKxQ2Edw7jfIx9aJtbQ_2(my, (&(*my).a));
	}
	break;
	default:
	{
		nimln_(638, "parsexml.nim");
		parseCharData_l7IS2MtBiHyCD179axgTwXw_8(my);
	}
	break;
	}
	nimln_(639, "parsexml.nim");
	{
		if (!!(!(((*my).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0))))) goto LA34_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_98));
	}
	LA34_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getTok_l7IS2MtBiHyCD179axgTwXw_10)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	nimfr_("getTok", "parsexml.nim");
	{
		nimln_(642, "parsexml.nim");
		while (1) {
			tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ lastKind;
			nimln_(643, "parsexml.nim");
			lastKind = (*my).kind;
			nimln_(644, "parsexml.nim");
			rawGetTok_l7IS2MtBiHyCD179axgTwXw_9(my);
			nimln_(645, "parsexml.nim");
			switch ((*my).kind) {
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 4):
			{
				nimln_(647, "parsexml.nim");
				{
					if (!(((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 1))&7U)))!=0)) goto LA6_;
					goto LA1;
				}
				LA6_: ;
			}
			break;
			case ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 3):
			{
				nimln_(649, "parsexml.nim");
				{
					NIM_BOOL T11_;
					T11_ = (NIM_BOOL)0;
					T11_ = (((*my).options &(1U<<((NU)(((tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ) 0))&7U)))!=0);
					if (T11_) goto LA12_;
					T11_ = ((4116 &(1U<<((NU)(lastKind)&15U)))!=0);
					LA12_: ;
					if (!T11_) goto LA13_;
					nimln_(650, "parsexml.nim");
					goto LA1;
				}
				LA13_: ;
			}
			break;
			default:
			{
				nimln_(651, "parsexml.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, next_l7IS2MtBiHyCD179axgTwXw_11)(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg* my) {
	nimfr_("next", "parsexml.nim");
	nimln_(655, "parsexml.nim");
	switch ((*my).state) {
	case ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 1):
	{
		nimln_(657, "parsexml.nim");
		getTok_l7IS2MtBiHyCD179axgTwXw_10(my);
	}
	break;
	case ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 0):
	{
		nimln_(659, "parsexml.nim");
		(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 1);
		nimln_(660, "parsexml.nim");
		getTok_l7IS2MtBiHyCD179axgTwXw_10(my);
		nimln_(661, "parsexml.nim");
		{
			NIM_BOOL T5_;
			T5_ = (NIM_BOOL)0;
			T5_ = ((*my).kind == ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 5));
			if (!(T5_)) goto LA6_;
			T5_ = eqStrings((*my).a, ((NimStringDesc*) &TM_mQUBeySWbTZT1BNx9b2ZGEg_99));
			LA6_: ;
			if (!T5_) goto LA7_;
			nimln_(663, "parsexml.nim");
			getTok_l7IS2MtBiHyCD179axgTwXw_10(my);
		}
		LA7_: ;
	}
	break;
	case ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 2):
	{
		nimln_(666, "parsexml.nim");
		{
			NI TM_mQUBeySWbTZT1BNx9b2ZGEg_100;
			if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(62))) goto LA12_;
			nimln_(667, "parsexml.nim");
			(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 10);
			nimln_(668, "parsexml.nim");
			TM_mQUBeySWbTZT1BNx9b2ZGEg_100 = addInt((*my).Sup.bufpos, ((NI) 1));
			(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_100);
			nimln_(669, "parsexml.nim");
			(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 1);
		}
		goto LA10_;
		LA12_: ;
		{
			tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T17_;
			nimln_(670, "parsexml.nim");
			if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(47))) goto LA15_;
			nimln_(671, "parsexml.nim");
			T17_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
			T17_ = &my->Sup;
			(*my).Sup.bufpos = handleRefillChar_IwUEvMBOLRY9cqyar6XKEaw_4(T17_, (*my).Sup.bufpos);
			nimln_(672, "parsexml.nim");
			{
				NI TM_mQUBeySWbTZT1BNx9b2ZGEg_101;
				if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(62))) goto LA20_;
				nimln_(673, "parsexml.nim");
				(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 10);
				nimln_(674, "parsexml.nim");
				TM_mQUBeySWbTZT1BNx9b2ZGEg_101 = addInt((*my).Sup.bufpos, ((NI) 1));
				(*my).Sup.bufpos = (NI)(TM_mQUBeySWbTZT1BNx9b2ZGEg_101);
				nimln_(675, "parsexml.nim");
				(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 3);
			}
			goto LA18_;
			LA20_: ;
			{
				nimln_(677, "parsexml.nim");
				markError_NBD9ac4OsXD4FKAOrCZcgTQparsexml(my, ((tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw) 5));
			}
			LA18_: ;
		}
		goto LA10_;
		LA15_: ;
		{
			nimln_(679, "parsexml.nim");
			parseAttribute_l7IS2MtBiHyCD179axgTwXw_7(my);
		}
		LA10_: ;
	}
	break;
	case ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 3):
	{
		nimln_(682, "parsexml.nim");
		(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 1);
		nimln_(683, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 7);
		nimln_(684, "parsexml.nim");
		{
			if (!!(((*my).c == 0))) goto LA27_;
			nimln_(685, "parsexml.nim");
			unsureAsgnRef((void**) (&(*my).a), copyString((*my).c));
		}
		LA27_: ;
	}
	break;
	case ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 4):
	{
		nimln_(687, "parsexml.nim");
		(*my).kind = ((tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ) 0);
		nimln_(688, "parsexml.nim");
		(*my).state = ((tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg) 1);
	}
	break;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parsexmlInit000)(void) {
	nimfr_("parsexml", "parsexml.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parsexmlDatInit000)(void) {
static TNimNode* TM_mQUBeySWbTZT1BNx9b2ZGEg_102[8];
static TNimNode* TM_mQUBeySWbTZT1BNx9b2ZGEg_103[14];
NI TM_mQUBeySWbTZT1BNx9b2ZGEg_105;
static char* NIM_CONST TM_mQUBeySWbTZT1BNx9b2ZGEg_104[14] = {
"xmlError", 
"xmlEof", 
"xmlCharData", 
"xmlWhitespace", 
"xmlComment", 
"xmlPI", 
"xmlElementStart", 
"xmlElementEnd", 
"xmlElementOpen", 
"xmlAttribute", 
"xmlElementClose", 
"xmlCData", 
"xmlEntity", 
"xmlSpecial"};
static TNimNode* TM_mQUBeySWbTZT1BNx9b2ZGEg_106[9];
NI TM_mQUBeySWbTZT1BNx9b2ZGEg_108;
static char* NIM_CONST TM_mQUBeySWbTZT1BNx9b2ZGEg_107[9] = {
"errNone", 
"errEndOfCDataExpected", 
"errNameExpected", 
"errSemicolonExpected", 
"errQmGtExpected", 
"errGtExpected", 
"errEqExpected", 
"errQuoteExpected", 
"errEndOfCommentExpected"};
static TNimNode* TM_mQUBeySWbTZT1BNx9b2ZGEg_109[5];
NI TM_mQUBeySWbTZT1BNx9b2ZGEg_111;
static char* NIM_CONST TM_mQUBeySWbTZT1BNx9b2ZGEg_110[5] = {
"stateStart", 
"stateNormal", 
"stateAttr", 
"stateEmptyElementTag", 
"stateError"};
static TNimNode* TM_mQUBeySWbTZT1BNx9b2ZGEg_112[2];
NI TM_mQUBeySWbTZT1BNx9b2ZGEg_114;
static char* NIM_CONST TM_mQUBeySWbTZT1BNx9b2ZGEg_113[2] = {
"reportWhitespace", 
"reportComments"};
static TNimNode TM_mQUBeySWbTZT1BNx9b2ZGEg_0[44];
NTI_AbcNJUHmXZCVg300UxOzLg_.size = sizeof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg);
NTI_AbcNJUHmXZCVg300UxOzLg_.kind = 17;
NTI_AbcNJUHmXZCVg300UxOzLg_.base = (&NTI_B6cGbTPhMsqMovc9cOcIHRw_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[0] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[1];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[1].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[1].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, a);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[1].name = "a";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[1] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[2];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[2].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[2].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, b);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[2].name = "b";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[2] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[3];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[3].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[3].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, c);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[3].name = "c";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[3] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[4];
NTI_Qknhzh4VTsYTMpU18vpBLQ_.size = sizeof(tyEnum_XmlEventKind_Qknhzh4VTsYTMpU18vpBLQ);
NTI_Qknhzh4VTsYTMpU18vpBLQ_.kind = 14;
NTI_Qknhzh4VTsYTMpU18vpBLQ_.base = 0;
NTI_Qknhzh4VTsYTMpU18vpBLQ_.flags = 3;
for (TM_mQUBeySWbTZT1BNx9b2ZGEg_105 = 0; TM_mQUBeySWbTZT1BNx9b2ZGEg_105 < 14; TM_mQUBeySWbTZT1BNx9b2ZGEg_105++) {
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_105+5].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_105+5].offset = TM_mQUBeySWbTZT1BNx9b2ZGEg_105;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_105+5].name = TM_mQUBeySWbTZT1BNx9b2ZGEg_104[TM_mQUBeySWbTZT1BNx9b2ZGEg_105];
TM_mQUBeySWbTZT1BNx9b2ZGEg_103[TM_mQUBeySWbTZT1BNx9b2ZGEg_105] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_105+5];
}
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[19].len = 14; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[19].kind = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[19].sons = &TM_mQUBeySWbTZT1BNx9b2ZGEg_103[0];
NTI_Qknhzh4VTsYTMpU18vpBLQ_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[19];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[4].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[4].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, kind);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[4].typ = (&NTI_Qknhzh4VTsYTMpU18vpBLQ_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[4].name = "kind";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[4] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[20];
NTI_F9abdZJggjbagkcCFgqbI9bw_.size = sizeof(tyEnum_XmlErrorKind_F9abdZJggjbagkcCFgqbI9bw);
NTI_F9abdZJggjbagkcCFgqbI9bw_.kind = 14;
NTI_F9abdZJggjbagkcCFgqbI9bw_.base = 0;
NTI_F9abdZJggjbagkcCFgqbI9bw_.flags = 3;
for (TM_mQUBeySWbTZT1BNx9b2ZGEg_108 = 0; TM_mQUBeySWbTZT1BNx9b2ZGEg_108 < 9; TM_mQUBeySWbTZT1BNx9b2ZGEg_108++) {
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_108+21].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_108+21].offset = TM_mQUBeySWbTZT1BNx9b2ZGEg_108;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_108+21].name = TM_mQUBeySWbTZT1BNx9b2ZGEg_107[TM_mQUBeySWbTZT1BNx9b2ZGEg_108];
TM_mQUBeySWbTZT1BNx9b2ZGEg_106[TM_mQUBeySWbTZT1BNx9b2ZGEg_108] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_108+21];
}
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[30].len = 9; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[30].kind = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[30].sons = &TM_mQUBeySWbTZT1BNx9b2ZGEg_106[0];
NTI_F9abdZJggjbagkcCFgqbI9bw_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[30];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[20].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[20].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, err);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[20].typ = (&NTI_F9abdZJggjbagkcCFgqbI9bw_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[20].name = "err";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[5] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[31];
NTI_W9a0n9bkhFkprfWuBVM2z9bBg_.size = sizeof(tyEnum_ParserState_W9a0n9bkhFkprfWuBVM2z9bBg);
NTI_W9a0n9bkhFkprfWuBVM2z9bBg_.kind = 14;
NTI_W9a0n9bkhFkprfWuBVM2z9bBg_.base = 0;
NTI_W9a0n9bkhFkprfWuBVM2z9bBg_.flags = 3;
for (TM_mQUBeySWbTZT1BNx9b2ZGEg_111 = 0; TM_mQUBeySWbTZT1BNx9b2ZGEg_111 < 5; TM_mQUBeySWbTZT1BNx9b2ZGEg_111++) {
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_111+32].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_111+32].offset = TM_mQUBeySWbTZT1BNx9b2ZGEg_111;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_111+32].name = TM_mQUBeySWbTZT1BNx9b2ZGEg_110[TM_mQUBeySWbTZT1BNx9b2ZGEg_111];
TM_mQUBeySWbTZT1BNx9b2ZGEg_109[TM_mQUBeySWbTZT1BNx9b2ZGEg_111] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_111+32];
}
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[37].len = 5; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[37].kind = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[37].sons = &TM_mQUBeySWbTZT1BNx9b2ZGEg_109[0];
NTI_W9a0n9bkhFkprfWuBVM2z9bBg_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[37];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[31].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[31].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, state);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[31].typ = (&NTI_W9a0n9bkhFkprfWuBVM2z9bBg_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[31].name = "state";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[6] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[38];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[38].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[38].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, filename);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[38].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[38].name = "filename";
TM_mQUBeySWbTZT1BNx9b2ZGEg_102[7] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[39];
NTI_VCopfBMD18d0QUQlFvdMUQ_.size = sizeof(tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ);
NTI_VCopfBMD18d0QUQlFvdMUQ_.kind = 14;
NTI_VCopfBMD18d0QUQlFvdMUQ_.base = 0;
NTI_VCopfBMD18d0QUQlFvdMUQ_.flags = 3;
for (TM_mQUBeySWbTZT1BNx9b2ZGEg_114 = 0; TM_mQUBeySWbTZT1BNx9b2ZGEg_114 < 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_114++) {
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_114+40].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_114+40].offset = TM_mQUBeySWbTZT1BNx9b2ZGEg_114;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_114+40].name = TM_mQUBeySWbTZT1BNx9b2ZGEg_113[TM_mQUBeySWbTZT1BNx9b2ZGEg_114];
TM_mQUBeySWbTZT1BNx9b2ZGEg_112[TM_mQUBeySWbTZT1BNx9b2ZGEg_114] = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[TM_mQUBeySWbTZT1BNx9b2ZGEg_114+40];
}
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[42].len = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[42].kind = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[42].sons = &TM_mQUBeySWbTZT1BNx9b2ZGEg_112[0];
NTI_VCopfBMD18d0QUQlFvdMUQ_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[42];
NTI_smopboHXIPvj5YRsyy63RA_.size = sizeof(tySet_tyEnum_XmlParseOption_VCopfBMD18d0QUQlFvdMUQ);
NTI_smopboHXIPvj5YRsyy63RA_.kind = 19;
NTI_smopboHXIPvj5YRsyy63RA_.base = (&NTI_VCopfBMD18d0QUQlFvdMUQ_);
NTI_smopboHXIPvj5YRsyy63RA_.flags = 3;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[43].len = 0; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[43].kind = 0;
NTI_smopboHXIPvj5YRsyy63RA_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[43];
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[39].kind = 1;
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[39].offset = offsetof(tyObject_XmlParser_AbcNJUHmXZCVg300UxOzLg, options);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[39].typ = (&NTI_smopboHXIPvj5YRsyy63RA_);
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[39].name = "options";
TM_mQUBeySWbTZT1BNx9b2ZGEg_0[0].len = 8; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[0].kind = 2; TM_mQUBeySWbTZT1BNx9b2ZGEg_0[0].sons = &TM_mQUBeySWbTZT1BNx9b2ZGEg_102[0];
NTI_AbcNJUHmXZCVg300UxOzLg_.node = &TM_mQUBeySWbTZT1BNx9b2ZGEg_0[0];
}

