/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/zip_libzip.o /home/dustin/Documents/EpubCLI/src/nimcache/zip_libzip.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w;
typedef struct tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ;
typedef struct tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA;
typedef struct tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, tyProc_KMLD9arBWwj7A9a5G9ba3YCBw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* para3);
typedef N_CDECL_PTR(NI32, tyProc_H1tVr9ax4jTNQwkX2LpUeOw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2);
typedef N_CDECL_PTR(void, tyProc_s43kOChzNSKU1t9bcnLvrtA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
typedef N_CDECL_PTR(NI32, tyProc_VcC1Qhc2DywbdyONe0ufXA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2);
typedef N_CDECL_PTR(void, tyProc_9akJZG5AZxIYPW6G9aVJioFQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32* para2, NI32* para3);
typedef N_CDECL_PTR(NI32, tyProc_GK8T7pIDb2GuXFntInSebA) (NI32 para1);
typedef N_CDECL_PTR(NI32, tyProc_ywda9cpVgAeB9cMfuBCzCBNQ) (NCSTRING para1, NI para2, NI32 para3, NI32 para4);
typedef N_CDECL_PTR(void, tyProc_qeagS9bWFM1WtD1VhsY4VuA) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1);
typedef N_CDECL_PTR(void, tyProc_N2Ue6JR5hi4nO2XVypB1dA) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1, NI32* para2, NI32* para3);
typedef N_CDECL_PTR(NCSTRING, tyProc_zpEp8DOj73iaCKEvmJQEjA) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1);
typedef N_CDECL_PTR(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA*, tyProc_rjCHawcACJ5HpUliwdrieg) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI32 para3);
typedef N_CDECL_PTR(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA*, tyProc_gF2D5XlD8ADdggf9a9aQDqEA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32 para3);
typedef N_CDECL_PTR(NI, tyProc_AWZd4VJtky42A2Q9bGOITAg) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1, void* para2, NI para3);
typedef N_CDECL_PTR(NCSTRING, tyProc_pwl7a9b46wUg53Bf5nx9cCDA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32* para2, NI32 para3);
typedef N_CDECL_PTR(NI32, tyProc_TLCYD2T6XAS7lt687jkk4Q) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32 para3);
typedef N_CDECL_PTR(NCSTRING, tyProc_0lTP8i6jNRDPe6Dc5In1sA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32* para3, NI32 para4);
typedef N_CDECL_PTR(NCSTRING, tyProc_B9bKt7gQkogrPDbmiZvdmzQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32 para3);
typedef N_CDECL_PTR(NI32, tyProc_HtNnEZ6SlJHKAg6IKCIOBQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
typedef N_CDECL_PTR(NI32, tyProc_ndrty5SYbsv78yZIxTJj1g) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI32 para3);
typedef N_CDECL_PTR(tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w*, tyProc_pDOearIUbEwXlibTkLHtPg) (NCSTRING para1, NI32 para2, NI32* para3);
typedef N_CDECL_PTR(NI32, tyProc_mbn8krOdpHO9aQ3JxK7ZxQg) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NCSTRING para3);
typedef N_CDECL_PTR(NI32, tyProc_rHnZoEcCxR5OHELM09bC2Xw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* para3);
typedef N_CDECL_PTR(NI32, tyProc_P02cG27EAYueSSG9bdesrrQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NCSTRING para3, NI32 para4);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_GSBm17wdBKzbu9cFYEMJCwQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, void* para2, NI para3, NI32 para4);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_KG9avVdNOE7fyG6otoSdP6g) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI para3, NI para4);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_ScrxXhRlzuRj7Ly4xt6zlw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, FILE* para2, NI para3, NI para4);
typedef N_CDECL_PTR(void, tyProc_9a29cY6QPl1azGGNUtbfe9bqw) (tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* para1);
typedef N_CDECL_PTR(NI, tyProc_zcB9a56s49aVEtMV9cHJn9cifw) (void* state, void* data, NI length, NI32 cmd);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_AjHztqyloiUoPLzBpLQj9bw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, tyProc_zcB9a56s49aVEtMV9cHJn9cifw para2, void* para3);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_XkHDTnqM1Bus8cw9batSyEQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para2, NI32 para3, NI32 para4, NI para5, NI para6);
typedef N_CDECL_PTR(NI32, tyProc_PB7LguluKApPpoaVDfQuDA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI32 para3, tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg* para4);
typedef N_CDECL_PTR(NI32, tyProc_VcObOGTaQcQ5dd3o2ayM9aQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32 para3, tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg* para4);
typedef N_CDECL_PTR(void, tyProc_0gXDgv9bvgsFFQ9bYswphadg) (tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg* para1);
typedef N_CDECL_PTR(NCSTRING, tyProc_Z25OqjhpLsYxv3Senn2anw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
struct tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA {
char dummy;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w {
char dummy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ {
char dummy;
};
struct tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg {
NCSTRING name;
NI32 index;
NI32 crc;
NI64 mtime;
NI size;
NI compSize;
NI16 compMethod;
NI16 encryptionMethod;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_CsxO0JIA56k3hrrF5NQNmQ_2;
tyProc_KMLD9arBWwj7A9a5G9ba3YCBw Dl_141519_;
tyProc_H1tVr9ax4jTNQwkX2LpUeOw Dl_141524_;
tyProc_s43kOChzNSKU1t9bcnLvrtA Dl_141528_;
tyProc_VcC1Qhc2DywbdyONe0ufXA Dl_141531_;
tyProc_s43kOChzNSKU1t9bcnLvrtA Dl_141535_;
tyProc_9akJZG5AZxIYPW6G9aVJioFQ Dl_141538_;
tyProc_GK8T7pIDb2GuXFntInSebA Dl_141545_;
tyProc_ywda9cpVgAeB9cMfuBCzCBNQ Dl_141548_;
tyProc_qeagS9bWFM1WtD1VhsY4VuA Dl_141554_;
tyProc_qeagS9bWFM1WtD1VhsY4VuA Dl_141557_;
tyProc_N2Ue6JR5hi4nO2XVypB1dA Dl_141560_;
tyProc_zpEp8DOj73iaCKEvmJQEjA Dl_141567_;
tyProc_rjCHawcACJ5HpUliwdrieg Dl_141570_;
tyProc_gF2D5XlD8ADdggf9a9aQDqEA Dl_141575_;
tyProc_AWZd4VJtky42A2Q9bGOITAg Dl_141580_;
tyProc_pwl7a9b46wUg53Bf5nx9cCDA Dl_141585_;
tyProc_TLCYD2T6XAS7lt687jkk4Q Dl_141591_;
tyProc_0lTP8i6jNRDPe6Dc5In1sA Dl_141596_;
tyProc_B9bKt7gQkogrPDbmiZvdmzQ Dl_141603_;
tyProc_HtNnEZ6SlJHKAg6IKCIOBQ Dl_141608_;
tyProc_ndrty5SYbsv78yZIxTJj1g Dl_141611_;
tyProc_pDOearIUbEwXlibTkLHtPg Dl_141616_;
tyProc_mbn8krOdpHO9aQ3JxK7ZxQg Dl_141622_;
tyProc_rHnZoEcCxR5OHELM09bC2Xw Dl_141627_;
tyProc_ndrty5SYbsv78yZIxTJj1g Dl_141632_;
tyProc_TLCYD2T6XAS7lt687jkk4Q Dl_141637_;
tyProc_P02cG27EAYueSSG9bdesrrQ Dl_141642_;
tyProc_GSBm17wdBKzbu9cFYEMJCwQ Dl_141648_;
tyProc_KG9avVdNOE7fyG6otoSdP6g Dl_141654_;
tyProc_ScrxXhRlzuRj7Ly4xt6zlw Dl_141660_;
tyProc_9a29cY6QPl1azGGNUtbfe9bqw Dl_141666_;
tyProc_AjHztqyloiUoPLzBpLQj9bw Dl_141669_;
tyProc_XkHDTnqM1Bus8cw9batSyEQ Dl_141674_;
tyProc_PB7LguluKApPpoaVDfQuDA Dl_141682_;
tyProc_VcObOGTaQcQ5dd3o2ayM9aQ Dl_141688_;
tyProc_0gXDgv9bvgsFFQ9bYswphadg Dl_141694_;
tyProc_Z25OqjhpLsYxv3Senn2anw Dl_141697_;
tyProc_VcC1Qhc2DywbdyONe0ufXA Dl_141700_;
tyProc_HtNnEZ6SlJHKAg6IKCIOBQ Dl_141704_;
tyProc_HtNnEZ6SlJHKAg6IKCIOBQ Dl_141707_;
TNimType NTI_A7lXyJU3hil1EXZ8yyG9clA_;
TNimType NTI_1NZBc7g9cNZTsFd9coh2swKg_;
TNimType NTI_m6P71L7VU9azMWkxLPHUh7w_;
TNimType NTI_WceCYaMZ7nzO5pMSW1cStg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_4, "libzip.so", 9);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_6, "libzip.so.4", 11);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_8, "libzip.so.2", 11);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_10, "libzip.so.1", 11);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_12, "libzip.so.0", 11);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_14, "libzip2.so", 10);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_16, "libzip2.so.4", 12);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_18, "libzip2.so.2", 12);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_20, "libzip2.so.1", 12);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_22, "libzip2.so.0", 12);
STRING_LITERAL(TM_CsxO0JIA56k3hrrF5NQNmQ_23, "libzip(|2).so(|.4|.2|.1|.0)", 27);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, zip_libzipInit000)(void) {
	nimfr_("libzip", "libzip.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, zip_libzipDatInit000)(void) {
static TNimNode TM_CsxO0JIA56k3hrrF5NQNmQ_0[2];
NTI_A7lXyJU3hil1EXZ8yyG9clA_.size = sizeof(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA);
NTI_A7lXyJU3hil1EXZ8yyG9clA_.kind = 18;
NTI_A7lXyJU3hil1EXZ8yyG9clA_.base = 0;
NTI_A7lXyJU3hil1EXZ8yyG9clA_.flags = 3;
TM_CsxO0JIA56k3hrrF5NQNmQ_0[0].len = 0; TM_CsxO0JIA56k3hrrF5NQNmQ_0[0].kind = 2;
NTI_A7lXyJU3hil1EXZ8yyG9clA_.node = &TM_CsxO0JIA56k3hrrF5NQNmQ_0[0];
NTI_1NZBc7g9cNZTsFd9coh2swKg_.size = sizeof(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA*);
NTI_1NZBc7g9cNZTsFd9coh2swKg_.kind = 21;
NTI_1NZBc7g9cNZTsFd9coh2swKg_.base = (&NTI_A7lXyJU3hil1EXZ8yyG9clA_);
NTI_1NZBc7g9cNZTsFd9coh2swKg_.flags = 3;
NTI_m6P71L7VU9azMWkxLPHUh7w_.size = sizeof(tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w);
NTI_m6P71L7VU9azMWkxLPHUh7w_.kind = 18;
NTI_m6P71L7VU9azMWkxLPHUh7w_.base = 0;
NTI_m6P71L7VU9azMWkxLPHUh7w_.flags = 3;
TM_CsxO0JIA56k3hrrF5NQNmQ_0[1].len = 0; TM_CsxO0JIA56k3hrrF5NQNmQ_0[1].kind = 2;
NTI_m6P71L7VU9azMWkxLPHUh7w_.node = &TM_CsxO0JIA56k3hrrF5NQNmQ_0[1];
NTI_WceCYaMZ7nzO5pMSW1cStg_.size = sizeof(tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w*);
NTI_WceCYaMZ7nzO5pMSW1cStg_.kind = 21;
NTI_WceCYaMZ7nzO5pMSW1cStg_.base = (&NTI_m6P71L7VU9azMWkxLPHUh7w_);
NTI_WceCYaMZ7nzO5pMSW1cStg_.flags = 3;
if (!((TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_4))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_6))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_8))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_10))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_12))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_14))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_16))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_18))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_20))
||(TM_CsxO0JIA56k3hrrF5NQNmQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_22))
)) nimLoadLibraryError((NimStringDesc*) &TM_CsxO0JIA56k3hrrF5NQNmQ_23);
	Dl_141519_ = (tyProc_KMLD9arBWwj7A9a5G9ba3YCBw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_add");
	Dl_141524_ = (tyProc_H1tVr9ax4jTNQwkX2LpUeOw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_add_dir");
	Dl_141528_ = (tyProc_s43kOChzNSKU1t9bcnLvrtA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_close");
	Dl_141531_ = (tyProc_VcC1Qhc2DywbdyONe0ufXA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_delete");
	Dl_141535_ = (tyProc_s43kOChzNSKU1t9bcnLvrtA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_error_clear");
	Dl_141538_ = (tyProc_9akJZG5AZxIYPW6G9aVJioFQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_error_get");
	Dl_141545_ = (tyProc_GK8T7pIDb2GuXFntInSebA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_error_get_sys_type");
	Dl_141548_ = (tyProc_ywda9cpVgAeB9cMfuBCzCBNQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_error_to_str");
	Dl_141554_ = (tyProc_qeagS9bWFM1WtD1VhsY4VuA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_fclose");
	Dl_141557_ = (tyProc_qeagS9bWFM1WtD1VhsY4VuA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_file_error_clear");
	Dl_141560_ = (tyProc_N2Ue6JR5hi4nO2XVypB1dA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_file_error_get");
	Dl_141567_ = (tyProc_zpEp8DOj73iaCKEvmJQEjA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_file_strerror");
	Dl_141570_ = (tyProc_rjCHawcACJ5HpUliwdrieg) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_fopen");
	Dl_141575_ = (tyProc_gF2D5XlD8ADdggf9a9aQDqEA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_fopen_index");
	Dl_141580_ = (tyProc_AWZd4VJtky42A2Q9bGOITAg) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_fread");
	Dl_141585_ = (tyProc_pwl7a9b46wUg53Bf5nx9cCDA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_get_archive_comment");
	Dl_141591_ = (tyProc_TLCYD2T6XAS7lt687jkk4Q) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_get_archive_flag");
	Dl_141596_ = (tyProc_0lTP8i6jNRDPe6Dc5In1sA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_get_file_comment");
	Dl_141603_ = (tyProc_B9bKt7gQkogrPDbmiZvdmzQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_get_name");
	Dl_141608_ = (tyProc_HtNnEZ6SlJHKAg6IKCIOBQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_get_num_files");
	Dl_141611_ = (tyProc_ndrty5SYbsv78yZIxTJj1g) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_name_locate");
	Dl_141616_ = (tyProc_pDOearIUbEwXlibTkLHtPg) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_open");
	Dl_141622_ = (tyProc_mbn8krOdpHO9aQ3JxK7ZxQg) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_rename");
	Dl_141627_ = (tyProc_rHnZoEcCxR5OHELM09bC2Xw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_replace");
	Dl_141632_ = (tyProc_ndrty5SYbsv78yZIxTJj1g) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_set_archive_comment");
	Dl_141637_ = (tyProc_TLCYD2T6XAS7lt687jkk4Q) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_set_archive_flag");
	Dl_141642_ = (tyProc_P02cG27EAYueSSG9bdesrrQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_set_file_comment");
	Dl_141648_ = (tyProc_GSBm17wdBKzbu9cFYEMJCwQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_buffer");
	Dl_141654_ = (tyProc_KG9avVdNOE7fyG6otoSdP6g) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_file");
	Dl_141660_ = (tyProc_ScrxXhRlzuRj7Ly4xt6zlw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_filep");
	Dl_141666_ = (tyProc_9a29cY6QPl1azGGNUtbfe9bqw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_free");
	Dl_141669_ = (tyProc_AjHztqyloiUoPLzBpLQj9bw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_function");
	Dl_141674_ = (tyProc_XkHDTnqM1Bus8cw9batSyEQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_source_zip");
	Dl_141682_ = (tyProc_PB7LguluKApPpoaVDfQuDA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_stat");
	Dl_141688_ = (tyProc_VcObOGTaQcQ5dd3o2ayM9aQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_stat_index");
	Dl_141694_ = (tyProc_0gXDgv9bvgsFFQ9bYswphadg) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_stat_init");
	Dl_141697_ = (tyProc_Z25OqjhpLsYxv3Senn2anw) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_strerror");
	Dl_141700_ = (tyProc_VcC1Qhc2DywbdyONe0ufXA) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_unchange");
	Dl_141704_ = (tyProc_HtNnEZ6SlJHKAg6IKCIOBQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_unchange_all");
	Dl_141707_ = (tyProc_HtNnEZ6SlJHKAg6IKCIOBQ) nimGetProcAddr(TM_CsxO0JIA56k3hrrF5NQNmQ_2, "zip_unchange_archive");
}

