/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/.choosenim/toolchains/nim-0.18.0/lib -o /home/dustin/Documents/EpubCLI/src/nimcache/zip_zipfiles.o /home/dustin/Documents/EpubCLI/src/nimcache/zip_zipfiles.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg;
typedef struct tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA;
typedef struct tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw;
typedef struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_Z25OqjhpLsYxv3Senn2anw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g {
  RootObj Sup;
tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode;
tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* w;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w*, tyProc_pDOearIUbEwXlibTkLHtPg) (NCSTRING para1, NI32 para2, NI32* para3);
typedef N_CDECL_PTR(void, tyProc_s43kOChzNSKU1t9bcnLvrtA) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
typedef N_CDECL_PTR(NI32, tyProc_H1tVr9ax4jTNQwkX2LpUeOw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_KG9avVdNOE7fyG6otoSdP6g) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI para3, NI para4);
typedef N_CDECL_PTR(NI32, tyProc_KMLD9arBWwj7A9a5G9ba3YCBw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* para3);
typedef N_CDECL_PTR(void, tyProc_9a29cY6QPl1azGGNUtbfe9bqw) (tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* para1);
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
typedef N_CDECL_PTR(void, tyProc_0gXDgv9bvgsFFQ9bYswphadg) (tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg* para1);
struct tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg {
NCSTRING name;
NI32 index;
NI32 crc;
NI64 mtime;
NI size;
NI compSize;
NI16 compMethod;
NI16 encryptionMethod;
};
typedef N_CDECL_PTR(NI, tyProc_zcB9a56s49aVEtMV9cHJn9cifw) (void* state, void* data, NI length, NI32 cmd);
typedef N_CDECL_PTR(tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ*, tyProc_AjHztqyloiUoPLzBpLQj9bw) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, tyProc_zcB9a56s49aVEtMV9cHJn9cifw para2, void* para3);
typedef N_CDECL_PTR(void, tyProc_qeagS9bWFM1WtD1VhsY4VuA) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1);
struct tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* f;
NIM_BOOL atEnd;
};
typedef N_CDECL_PTR(NI, tyProc_AWZd4VJtky42A2Q9bGOITAg) (tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* para1, void* para2, NI para3);
typedef N_CDECL_PTR(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA*, tyProc_rjCHawcACJ5HpUliwdrieg) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NCSTRING para2, NI32 para3);
typedef NU8 tyArray_S8ib5N31oJbAkqOZTlNg5Q[8192];
typedef N_CDECL_PTR(NI32, tyProc_HtNnEZ6SlJHKAg6IKCIOBQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1);
typedef N_CDECL_PTR(NCSTRING, tyProc_B9bKt7gQkogrPDbmiZvdmzQ) (tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w* para1, NI32 para2, NI32 para3);
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_Zip_m6P71L7VU9azMWkxLPHUh7w {
char dummy;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ {
char dummy;
};
struct tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA {
char dummy;
};
struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, zipError_lqXbAAf3kWcsqTbiGcPtzA)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open_fqqTQK1kKFLHJSm3p9aKSaQ)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(void, close_lqXbAAf3kWcsqTbiGcPtzA_2)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z);
N_LIB_PRIVATE N_NIMCALL(void, createDir_YWOmCRqvxK9bQfkEKYQUTNg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, addFile_09bLDyD9cOTeptuWtVdPiZsg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(NIM_BOOL, fileExists_yTPrfdEKg9cKCeSFUA6popQzipfiles)(NimStringDesc* filename);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, addFile_GvBaypbHOE9cG2MZ5Wy9avow)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* file);
N_LIB_PRIVATE N_CDECL(NI, mySourceCallback_f9cxxCqMr8y9cNtYyTvCh0UQ)(void* state, void* data, NI len, NI32 cmd);
N_LIB_PRIVATE N_NIMCALL(void, setPosition_2EvT6qzO8p9cFGMlCGqs59cA)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, readData_Gnwdizh7H5Q9cYivUoGHrVA)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
N_LIB_PRIVATE N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_LIB_PRIVATE N_NIMCALL(NI64, getTime_Ft5FFURWITtb9aR6Hjpq6UQ)(void);
N_NIMCALL(void, nimGCunref)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, addFile_9cK9aFrr8djaz3F6n2CjIO9bQ)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* src);
N_NIMCALL(void, nimGCref)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, fsClose_pHuZD29aVjle9bRvvwmTJrxA)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd_2rJXhj6jDkOzVia9bGaTGWw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_LIB_PRIVATE N_NIMCALL(NI, fsReadData_eigktkN9cuFBM82KGSlhy2A)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
N_LIB_PRIVATE N_NIMCALL(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*, newZipFileStream_xFxggmJ85Hxw7hLKr7WU5A)(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* f);
static N_NIMCALL(void, Marker_tyRef_ECNhha5f9aKPkq6d2zisi5w)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*, getStream_4CF0G4GYUOQ2Y9cILI0NP6A)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, extractFile_ljCyk5lrv9aZ4cP38bsskLg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* srcFile, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, writeData_lmaRetW0vPyY5hzlu3Ik7A)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
N_LIB_PRIVATE N_NIMCALL(void, flush_4ed7IXme7lqtClFI7s2sTQ)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_LIB_PRIVATE N_NIMCALL(void, extractFile_Jy1orkosVeMW8u7djefMUA)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* srcFile, NimStringDesc* dest);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_9argyMqCIlB1KDaxUuYVcmw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(void, extractAll_7N1W9aoc9cm5R0Z3JIadjhGg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start);
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyProc_Z25OqjhpLsYxv3Senn2anw Dl_141697_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_pDOearIUbEwXlibTkLHtPg Dl_141616_;
extern tyProc_s43kOChzNSKU1t9bcnLvrtA Dl_141528_;
extern tyProc_H1tVr9ax4jTNQwkX2LpUeOw Dl_141524_;
extern tyProc_s43kOChzNSKU1t9bcnLvrtA Dl_141535_;
extern tyProc_KG9avVdNOE7fyG6otoSdP6g Dl_141654_;
extern tyProc_KMLD9arBWwj7A9a5G9ba3YCBw Dl_141519_;
extern tyProc_9a29cY6QPl1azGGNUtbfe9bqw Dl_141666_;
extern tyProc_0gXDgv9bvgsFFQ9bYswphadg Dl_141694_;
extern tyProc_AjHztqyloiUoPLzBpLQj9bw Dl_141669_;
extern tyProc_qeagS9bWFM1WtD1VhsY4VuA Dl_141554_;
extern TNimType NTI_RShkcoDOPnoCVhtpN1hDPQ_;
TNimType NTI_VDEVErFsF9bEBISBr2zATNw_;
extern TNimType NTI_1NZBc7g9cNZTsFd9coh2swKg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern tyProc_AWZd4VJtky42A2Q9bGOITAg Dl_141580_;
TNimType NTI_ECNhha5f9aKPkq6d2zisi5w_;
extern tyProc_rjCHawcACJ5HpUliwdrieg Dl_141570_;
extern tyProc_HtNnEZ6SlJHKAg6IKCIOBQ Dl_141608_;
extern tyProc_B9bKt7gQkogrPDbmiZvdmzQ Dl_141603_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_gBLVNj8IKmYI9cCySk39cM8g_;
extern TNimType NTI_fVUBHvW79bXUw1j55Oo9avSQ_;
extern TNimType NTI_WceCYaMZ7nzO5pMSW1cStg_;
STRING_LITERAL(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_2, "\012not (z.mode == fmRead) ", 24);
STRING_LITERAL(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_3, "File \'", 6);
STRING_LITERAL(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_4, "\' does not exist", 16);
STRING_LITERAL(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_6, "Failed to create output file: ", 30);
STRING_LITERAL(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_7, "/", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, zipError_lqXbAAf3kWcsqTbiGcPtzA)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z) {
	tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
	NCSTRING T1_;
	nimfr_("zipError", "zipfiles.nim");
	e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
	nimln_(25, "zipfiles.nim");
	e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
	(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
	nimln_(26, "zipfiles.nim");
	T1_ = (NCSTRING)0;
	T1_ = Dl_141697_((*z).w);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), cstrToNimstr(T1_));
	nimln_(27, "zipfiles.nim");
	raiseException((Exception*)e, "IOError");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open_fqqTQK1kKFLHJSm3p9aKSaQ)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode) {
	NIM_BOOL result;
	NI32 err;
	NI32 flags;
	nimfr_("open", "zipfiles.nim");
	result = (NIM_BOOL)0;
	err = (NI32)0;
	flags = (NI32)0;
	nimln_(33, "zipfiles.nim");
	switch (mode) {
	case ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0):
	case ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 3):
	case ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 4):
	{
		nimln_(34, "zipfiles.nim");
		flags = ((NI32) 0);
	}
	break;
	case ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1):
	{
		nimln_(36, "zipfiles.nim");
		{
			NIM_BOOL T5_;
			T5_ = (NIM_BOOL)0;
			T5_ = nosexistsFile(filename);
			if (!T5_) goto LA6_;
			nosremoveFile(filename);
		}
		LA6_: ;
		nimln_(37, "zipfiles.nim");
		flags = ((NI32) 3);
	}
	break;
	case ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 2):
	{
		nimln_(38, "zipfiles.nim");
		flags = ((NI32) 1);
	}
	break;
	}
	nimln_(39, "zipfiles.nim");
	(*z).w = Dl_141616_(filename->data, flags, (&err));
	nimln_(40, "zipfiles.nim");
	(*z).mode = mode;
	nimln_(41, "zipfiles.nim");
	nimln_(398, "system.nim");
	nimln_(41, "zipfiles.nim");
	result = !(((*z).w == NIM_NIL));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_lqXbAAf3kWcsqTbiGcPtzA_2)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z) {
	nimfr_("close", "zipfiles.nim");
	nimln_(45, "zipfiles.nim");
	Dl_141528_((*z).w);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, createDir_YWOmCRqvxK9bQfkEKYQUTNg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dir) {
	NI32 T5_;
	nimfr_("createDir", "zipfiles.nim");
	nimln_(53, "zipfiles.nim");
	{
		if (!!(!(((*z).mode == ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0))))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_2));
	}
	LA3_: ;
	nimln_(54, "zipfiles.nim");
	T5_ = (NI32)0;
	T5_ = Dl_141524_((*z).w, dir->data);
	T5_;
	nimln_(55, "zipfiles.nim");
	Dl_141535_((*z).w);
	popFrame();
}

static N_INLINE(NIM_BOOL, fileExists_yTPrfdEKg9cKCeSFUA6popQzipfiles)(NimStringDesc* filename) {
	NIM_BOOL result;
	nimfr_("fileExists", "os.nim");
	result = (NIM_BOOL)0;
	nimln_(115, "os.nim");
	nimln_(116, "os.nim");
	result = nosexistsFile(filename);
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addFile_09bLDyD9cOTeptuWtVdPiZsg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest, NimStringDesc* src) {
	tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* zipsrc;
	nimfr_("addFile", "zipfiles.nim");
	nimln_(60, "zipfiles.nim");
	{
		if (!!(!(((*z).mode == ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0))))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_2));
	}
	LA3_: ;
	nimln_(61, "zipfiles.nim");
	{
		NIM_BOOL T7_;
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T10_;
		T7_ = (NIM_BOOL)0;
		T7_ = fileExists_yTPrfdEKg9cKCeSFUA6popQzipfiles(src);
		if (!!(T7_)) goto LA8_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(62, "zipfiles.nim");
		T10_ = (NimStringDesc*)0;
		T10_ = rawNewString(src->Sup.len + 22);
appendString(T10_, ((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_3));
appendString(T10_, src);
appendString(T10_, ((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_4));
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T10_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(62, "zipfiles.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA8_: ;
	nimln_(63, "zipfiles.nim");
	zipsrc = Dl_141654_((*z).w, src->data, ((NI) 0), ((NI) -1));
	nimln_(64, "zipfiles.nim");
	{
		if (!(zipsrc == NIM_NIL)) goto LA13_;
		nimln_(67, "zipfiles.nim");
		zipError_lqXbAAf3kWcsqTbiGcPtzA(z);
	}
	LA13_: ;
	nimln_(68, "zipfiles.nim");
	{
		NI32 T17_;
		T17_ = (NI32)0;
		T17_ = Dl_141519_((*z).w, dest->data, zipsrc);
		if (!(T17_ < ((NI32) 0))) goto LA18_;
		nimln_(69, "zipfiles.nim");
		Dl_141666_(zipsrc);
		nimln_(70, "zipfiles.nim");
		zipError_lqXbAAf3kWcsqTbiGcPtzA(z);
	}
	LA18_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addFile_GvBaypbHOE9cG2MZ5Wy9avow)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* file) {
	nimfr_("addFile", "zipfiles.nim");
	nimln_(75, "zipfiles.nim");
	addFile_09bLDyD9cOTeptuWtVdPiZsg(z, file, file);
	popFrame();
}

N_LIB_PRIVATE N_CDECL(NI, mySourceCallback_f9cxxCqMr8y9cNtYyTvCh0UQ)(void* state, void* data, NI len, NI32 cmd) {
	NI result;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* src;
	nimfr_("mySourceCallback", "zipfiles.nim");
	result = (NI)0;
	nimln_(79, "zipfiles.nim");
	src = ((tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*) (state));
	nimln_(80, "zipfiles.nim");
	switch (cmd) {
	case ((NI32) 0):
	{
		nimln_(82, "zipfiles.nim");
		{
			nimln_(398, "system.nim");
			nimln_(82, "zipfiles.nim");
			if (!!(((*src).setPositionImpl == NIM_NIL))) goto LA4_;
			setPosition_2EvT6qzO8p9cFGMlCGqs59cA(src, ((NI) 0));
		}
		LA4_: ;
	}
	break;
	case ((NI32) 1):
	{
		nimln_(84, "zipfiles.nim");
		result = readData_Gnwdizh7H5Q9cYivUoGHrVA(src, data, len);
	}
	break;
	case ((NI32) 2):
	{
		nimln_(85, "zipfiles.nim");
		close_4ed7IXme7lqtClFI7s2sTQ_2(src);
	}
	break;
	case ((NI32) 3):
	{
		tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg* stat;
		nimln_(87, "zipfiles.nim");
		stat = ((tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg*) (data));
		nimln_(88, "zipfiles.nim");
		Dl_141694_(stat);
		nimln_(89, "zipfiles.nim");
		(*stat).size = ((NI) 2147483646);
		nimln_(90, "zipfiles.nim");
		(*stat).mtime = getTime_Ft5FFURWITtb9aR6Hjpq6UQ();
		nimln_(91, "zipfiles.nim");
		result = ((NI)sizeof(tyObject_ZipStat_9cpZDfhdRKiDUXmJIyoVWfg));
	}
	break;
	case ((NI32) 4):
	{
		int* err;
		nimln_(93, "zipfiles.nim");
		err = ((int*) (data));
		nimln_(94, "zipfiles.nim");
		err[(((NI) 0))- 0] = ((NI32) 20);
		nimln_(95, "zipfiles.nim");
		err[(((NI) 1))- 0] = ((int) 0);
		nimln_(96, "zipfiles.nim");
		result = ((NI) 8);
	}
	break;
	case ((NI32) 5):
	{
		nimln_(97, "zipfiles.nim");
		nimGCunref(src);
	}
	break;
	case ((NI32) 14):
	{
		nimln_(100, "zipfiles.nim");
		result = ((NI) -1);
	}
	break;
	default:
	{
		nimln_(103, "zipfiles.nim");
		result = ((NI) -1);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addFile_9cK9aFrr8djaz3F6n2CjIO9bQ)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* src) {
	tyObject_ZipSource_kkwODOKF9cNJSgdg9cZdHqFQ* zipsrc;
	nimfr_("addFile", "zipfiles.nim");
	nimln_(108, "zipfiles.nim");
	{
		if (!!(!(((*z).mode == ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0))))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_2));
	}
	LA3_: ;
	nimln_(109, "zipfiles.nim");
	nimGCref(src);
	nimln_(110, "zipfiles.nim");
	zipsrc = Dl_141669_((*z).w, mySourceCallback_f9cxxCqMr8y9cNtYyTvCh0UQ, ((void*) (src)));
	nimln_(111, "zipfiles.nim");
	{
		if (!(zipsrc == NIM_NIL)) goto LA7_;
		zipError_lqXbAAf3kWcsqTbiGcPtzA(z);
	}
	LA7_: ;
	nimln_(112, "zipfiles.nim");
	{
		NI32 T11_;
		T11_ = (NI32)0;
		T11_ = Dl_141519_((*z).w, dest->data, zipsrc);
		if (!(T11_ < ((NI32) 0))) goto LA12_;
		nimln_(113, "zipfiles.nim");
		Dl_141666_(zipsrc);
		nimln_(114, "zipfiles.nim");
		zipError_lqXbAAf3kWcsqTbiGcPtzA(z);
	}
	LA12_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, fsClose_pHuZD29aVjle9bRvvwmTJrxA)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s) {
	nimfr_("fsClose", "zipfiles.nim");
	nimln_(126, "zipfiles.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI_VDEVErFsF9bEBISBr2zATNw_));
	Dl_141554_((*((tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*) (s))).f);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd_2rJXhj6jDkOzVia9bGaTGWw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s) {
	NIM_BOOL result;
	nimfr_("fsAtEnd", "zipfiles.nim");
	result = (NIM_BOOL)0;
	nimln_(127, "zipfiles.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI_VDEVErFsF9bEBISBr2zATNw_));
	result = (*((tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*) (s))).atEnd;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, fsReadData_eigktkN9cuFBM82KGSlhy2A)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen) {
	NI result;
	nimfr_("fsReadData", "zipfiles.nim");
	result = (NI)0;
	nimln_(129, "zipfiles.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI_VDEVErFsF9bEBISBr2zATNw_));
	result = Dl_141580_((*((tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*) (s))).f, buffer, bufLen);
	nimln_(130, "zipfiles.nim");
	{
		if (!(result == ((NI) 0))) goto LA3_;
		if (s) chckObj((*s).Sup.m_type, (&NTI_VDEVErFsF9bEBISBr2zATNw_));
		nimln_(131, "zipfiles.nim");
		(*((tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*) (s))).atEnd = NIM_TRUE;
	}
	LA3_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_ECNhha5f9aKPkq6d2zisi5w)(void* p, NI op) {
	tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw* a;
	a = (tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*, newZipFileStream_xFxggmJ85Hxw7hLKr7WU5A)(tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* f) {
	tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw* result;
	nimfr_("newZipFileStream", "zipfiles.nim");
	result = (tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*)0;
	nimln_(134, "zipfiles.nim");
	result = (tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*) newObj((&NTI_ECNhha5f9aKPkq6d2zisi5w_), sizeof(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw));
	(*result).Sup.Sup.m_type = (&NTI_VDEVErFsF9bEBISBr2zATNw_);
	nimln_(135, "zipfiles.nim");
	(*result).f = f;
	nimln_(136, "zipfiles.nim");
	(*result).atEnd = NIM_FALSE;
	nimln_(137, "zipfiles.nim");
	(*result).Sup.closeImpl = fsClose_pHuZD29aVjle9bRvvwmTJrxA;
	nimln_(138, "zipfiles.nim");
	(*result).Sup.readDataImpl = fsReadData_eigktkN9cuFBM82KGSlhy2A;
	nimln_(139, "zipfiles.nim");
	(*result).Sup.atEndImpl = fsAtEnd_2rJXhj6jDkOzVia9bGaTGWw;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*, getStream_4CF0G4GYUOQ2Y9cILI0NP6A)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* filename) {
	tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw* result;
	tyObject_ZipFile_A7lXyJU3hil1EXZ8yyG9clA* x;
	nimfr_("getStream", "zipfiles.nim");
	result = (tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*)0;
	nimln_(149, "zipfiles.nim");
	x = Dl_141570_((*z).w, filename->data, ((NI32) 0));
	nimln_(150, "zipfiles.nim");
	{
		nimln_(398, "system.nim");
		nimln_(150, "zipfiles.nim");
		if (!!((x == NIM_NIL))) goto LA3_;
		result = newZipFileStream_xFxggmJ85Hxw7hLKr7WU5A(x);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, extractFile_ljCyk5lrv9aZ4cP38bsskLg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* srcFile, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* dest) {
	tyArray_S8ib5N31oJbAkqOZTlNg5Q buf;
	tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw* strm;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T8_;
	nimfr_("extractFile", "zipfiles.nim");
	memset((void*)buf, 0, sizeof(buf));
	nimln_(164, "zipfiles.nim");
	strm = getStream_4CF0G4GYUOQ2Y9cILI0NP6A(z, srcFile);
	{
		nimln_(165, "zipfiles.nim");
		while (1) {
			NI bytesRead;
			tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T3_;
			nimln_(166, "zipfiles.nim");
			T3_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
			T3_ = &strm->Sup;
			bytesRead = readData_Gnwdizh7H5Q9cYivUoGHrVA(T3_, ((void*) ((&buf[(((NI) 0))- 0]))), ((NI) 8192));
			nimln_(167, "zipfiles.nim");
			{
				if (!(bytesRead <= ((NI) 0))) goto LA6_;
				goto LA1;
			}
			LA6_: ;
			nimln_(168, "zipfiles.nim");
			writeData_lmaRetW0vPyY5hzlu3Ik7A(dest, ((void*) ((&buf[(((NI) 0))- 0]))), bytesRead);
		}
	} LA1: ;
	nimln_(170, "zipfiles.nim");
	flush_4ed7IXme7lqtClFI7s2sTQ(dest);
	nimln_(171, "zipfiles.nim");
	T8_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T8_ = &strm->Sup;
	close_4ed7IXme7lqtClFI7s2sTQ_2(T8_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, extractFile_Jy1orkosVeMW8u7djefMUA)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* srcFile, NimStringDesc* dest) {
	tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* file;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T6_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T7_;
	nimfr_("extractFile", "zipfiles.nim");
	nimln_(175, "zipfiles.nim");
	file = newFileStream_9argyMqCIlB1KDaxUuYVcmw(dest, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	nimln_(176, "zipfiles.nim");
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T5_;
		if (!(file == 0)) goto LA3_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(177, "zipfiles.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(dest->Sup.len + 30);
appendString(T5_, ((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_6));
appendString(T5_, dest);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T5_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(177, "zipfiles.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA3_: ;
	nimln_(178, "zipfiles.nim");
	T6_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T6_ = &file->Sup;
	extractFile_ljCyk5lrv9aZ4cP38bsskLg(z, srcFile, T6_);
	nimln_(179, "zipfiles.nim");
	T7_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T7_ = &file->Sup;
	close_4ed7IXme7lqtClFI7s2sTQ_2(T7_);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_8;
	NI TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_9;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_8 = subInt(x.b, a);
	TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_9 = addInt((NI)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_8), ((NI) 1));
	L = (NI)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_9);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_10;
				NI TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_11;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_10 = addInt(i, a);
				if ((NU)((NI)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_10)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_10)];
				nimln_(3522, "system.nim");
				TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_11 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_11);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, extractAll_7N1W9aoc9cm5R0Z3JIadjhGg)(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g* z, NimStringDesc* dest) {
	nimfr_("extractAll", "zipfiles.nim");
	nimln_(183, "zipfiles.nim");
	noscreateDir(dest);
	{
		NimStringDesc* file;
		NI32 i;
		NI32 num;
		file = (NimStringDesc*)0;
		nimln_(155, "zipfiles.nim");
		i = ((NI32) 0);
		nimln_(156, "zipfiles.nim");
		num = Dl_141608_((*z).w);
		{
			nimln_(157, "zipfiles.nim");
			while (1) {
				NCSTRING T4_;
				NimStringDesc* T14_;
				NI TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_12;
				if (!(i < num)) goto LA3;
				nimln_(158, "zipfiles.nim");
				T4_ = (NCSTRING)0;
				T4_ = Dl_141603_((*z).w, i, ((NI32) 0));
				file = cstrToNimstr(T4_);
				nimln_(185, "zipfiles.nim");
				{
					NIM_BOOL T7_;
					NI T10_;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T11_;
					NimStringDesc* T12_;
					NimStringDesc* T13_;
					T7_ = (NIM_BOOL)0;
					T7_ = contains_bKoQGynT9bWCEn79aXG8be9aw(file, ((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_7));
					if (!T7_) goto LA8_;
					nimln_(186, "zipfiles.nim");
					T10_ = (NI)0;
					T10_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(file, ((NimStringDesc*) &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_7), ((NI) -1));
					T11_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), T10_);
					T12_ = (NimStringDesc*)0;
					T12_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(file, T11_);
					T13_ = (NimStringDesc*)0;
					T13_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(dest, T12_);
					noscreateDir(T13_);
				}
				LA8_: ;
				nimln_(187, "zipfiles.nim");
				T14_ = (NimStringDesc*)0;
				T14_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(dest, file);
				extractFile_Jy1orkosVeMW8u7djefMUA(z, file, T14_);
				nimln_(159, "zipfiles.nim");
				TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_12 = addInt(i, ((NI) 1));
				if (TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_12 < (-2147483647 -1) || TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_12 > 2147483647) raiseOverflow();
				i = (NI32)(TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_12);
			} LA3: ;
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, zip_zipfilesInit000)(void) {
	nimfr_("zipfiles", "zipfiles.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, zip_zipfilesDatInit000)(void) {
static TNimNode* TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_5[2];
static TNimNode* TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_13[2];
static TNimNode TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[6];
NTI_VDEVErFsF9bEBISBr2zATNw_.size = sizeof(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw);
NTI_VDEVErFsF9bEBISBr2zATNw_.kind = 17;
NTI_VDEVErFsF9bEBISBr2zATNw_.base = (&NTI_RShkcoDOPnoCVhtpN1hDPQ_);
NTI_VDEVErFsF9bEBISBr2zATNw_.flags = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_5[0] = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[1];
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[1].kind = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[1].offset = offsetof(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw, f);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[1].typ = (&NTI_1NZBc7g9cNZTsFd9coh2swKg_);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[1].name = "f";
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_5[1] = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[2];
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[2].kind = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[2].offset = offsetof(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw, atEnd);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[2].name = "atEnd";
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[0].len = 2; TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[0].kind = 2; TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[0].sons = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_5[0];
NTI_VDEVErFsF9bEBISBr2zATNw_.node = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[0];
NTI_ECNhha5f9aKPkq6d2zisi5w_.size = sizeof(tyObject_TZipFileStream_VDEVErFsF9bEBISBr2zATNw*);
NTI_ECNhha5f9aKPkq6d2zisi5w_.kind = 22;
NTI_ECNhha5f9aKPkq6d2zisi5w_.base = (&NTI_VDEVErFsF9bEBISBr2zATNw_);
NTI_ECNhha5f9aKPkq6d2zisi5w_.marker = Marker_tyRef_ECNhha5f9aKPkq6d2zisi5w;
NTI_gBLVNj8IKmYI9cCySk39cM8g_.size = sizeof(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g);
NTI_gBLVNj8IKmYI9cCySk39cM8g_.kind = 17;
NTI_gBLVNj8IKmYI9cCySk39cM8g_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_gBLVNj8IKmYI9cCySk39cM8g_.flags = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_13[0] = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[4];
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[4].kind = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[4].offset = offsetof(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g, mode);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[4].typ = (&NTI_fVUBHvW79bXUw1j55Oo9avSQ_);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[4].name = "mode";
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_13[1] = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[5];
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[5].kind = 1;
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[5].offset = offsetof(tyObject_ZipArchive_gBLVNj8IKmYI9cCySk39cM8g, w);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[5].typ = (&NTI_WceCYaMZ7nzO5pMSW1cStg_);
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[5].name = "w";
TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[3].len = 2; TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[3].kind = 2; TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[3].sons = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_13[0];
NTI_gBLVNj8IKmYI9cCySk39cM8g_.node = &TM_9cJ29c7WI5cjJ9av4m9cGgEBpA_0[3];
}

